### ISSUE TITLE
URGENTE Elegir templates Parallax para la web de Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#1]
Nos pidieron hacer una nueva web para Paty.

Necesitamos un template parallax para diseñar el sitio. Tiene que ser algo juvenil, amistoso, tirando a masculino, como es el estilo de Paty.

Buscalo en themeforest.net y pasame los links de las 3 opciones que más te gusten. Fijate que sean responsive. Necesitamos estas 3 opciones para el jueves o antes si es posible.

Referencia: http://7up.com.ar/web/#/comunidad

Aparte tené en cuenta si necesitás un asistente porque viene mucho trabajo en poco tiempo con esto.

**Comment by FAAREIA** [comment]
Hola Lea, el contenido va a ser como la página de seven up? Videos, redes sociales, contacto y algun que otro texto?

**Comment by LeandroBraier** [comment]
No exactamente. El mapa del sitio lo estamos pensando mañana, pero puedo
intuir que va a haber al menos una página de productos y una de noticias.
Te paso el sitio actual de Paty para que tengas en cuenta.

http://paty.com.ar/

On Tue, May 6, 2014 at 4:26 PM, Federico Arena notifications@github.comwrote:

> Hola Lea, el contenido va a ser como la página de seven up? Videos, redes
> sociales, contacto y algun que otro texto?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42347372
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Cómo va lea, pudiseron definir algo de la web al final?
Igualmente ahora a la noche voy a buscar un par de themes a ver si nos
pueden ayudar en algo.

Abrazo

**Comment by LeandroBraier** [comment]
Si viste un boceto de texto no le des bola. Es de otro sitio jeje

abrazo

**Comment by FAAREIA** [comment]
jajajaja, como que de otro sitio?
De paty no tienen nada aún? Convendría buscar theme con algun contenido ya
fijo.
Avisa si sigue siendo para mañana

2014-05-07 22:29 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Si, pero pensalo como el de 7up y listo. Busca un template parecido.

**Comment by FAAREIA** [comment]
oka, más tarde te envío.

**Comment by LeandroBraier** [comment]
gracias!

2014-05-07 22:57 GMT-03:00 Federico Arena notifications@github.com:

> oka, más tarde te envío.
> 
> El 7 de mayo de 2014, 22:57, LeandroBraiernotifications@github.comescribió:
> 
> > Si, pero pensalo como el de 7up y listo. Busca un template parecido.
> > 
> > Federico Arena notifications@github.com escribió:
> > 
> > jajajaja,comoquedeotrositio?Depatynotienennadaaún?Convendríabuscarthemeconalguncontenidoyafijo.Avisasisiguesiendoparamañ
> > ana2014-05-0722:29GMT-03:00LeandroBraiernotifications@github.com:
> > 
> > Sivisteunbocetodetextonoledesbola.Esdeotrositiojejeabrazo—ReplytothisemaildirectlyorviewitonGitHubhttps://
> > 
> > github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42504598.ReplytothisemaildirectlyorviewitonGitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42505964>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42506002
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, estructuralmente estos están bien:

http://demo.codepark.co/?theme=floyd

http://themeforest.net/item/spaceman-parallax-design-studio-template/full_screen_preview/5448364 

http://themeforest.net/item/color-room-responsive-parallax-template/full_screen_preview/5207800 

Pero como vos decís, lo estético no va con Paty.

Entonces necesito que sigas buscando templates de este tipo pero que podamos reutilizar la estética en un 80%, como me cuenta Eze que ocurrió con el sitio de Dánica. Cuando se aprobó el template ya el sitio tenía un 80% armado. Si bien después requirió mucho trabajo, hacerlo desde scratch hubiera llevado mucho más.

Y tené en cuenta que tenemois poquito tiempo para lanzar este sitio, incluso menos que el que tuvimos para el de Dánica.

**Comment by LeandroBraier** [comment]
Si no encontrás en theme forest buscá en otros repositorios de templates, abramos la búsqueda.

**Comment by FAAREIA** [comment]
Es que ahi esta el tema Lea, algo ser algo tan particular no encuentro/hay
nada.

_Busqúe en Theme Forest y Monster Template lo siguiente:_
"burger parallax"
"hamburger parallax"
"kid parallax"
"drawn parallax"
"food parallax"
"burger"

Algunos arrojan 1, 3 o varios resultados que tampoco sirven. Y encima
necesitamos algo distinto a lo común, que es lo que venden estos sitios.
El de Dánica se encontró pero porque habla de cocina y comida, aca es
hamburguesa y solo eso.

Estuve buscando también en google de otros sitios que ofrezcan templates no
encontré ningun otro. Sería menos dificil si no es parallax también.

¿Cómo decis de seguir?

## 

Federico Arena
Diseño & Desarrollo Web
C: +54 11 15.6582.2442

http://faareia.com/
http://faareia.com/

**Comment by LeandroBraier** [comment]
No te centres tanto en hamburguesa en sí, sino en cosas que pueden ser distintas pero la estética pegue. Pueden ser panchos, comida rápida, gaseosas como 7up etc. Los colores principales de Paty son el rojo y el blanco., tené en cuenta eso si querés, pero es más importante para la estética el que esté apuntado a grupos de amigos, jovenes, juntadas, etc, que el hecho de que el producto sea un hamburguesa, entendés?

**Comment by FAAREIA** [comment]
oka, buenisimo. Sigo buscando entonces, en esos dos sitios

## 

Federico Arena
Diseño & Desarrollo Web
C: +54 11 15.6582.2442

http://faareia.com/
http://faareia.com/

**Comment by LeandroBraier** [comment]
O en otros sitios de templates, no te restrinjas solo a ese. Si encontrás
uno bueno en otro sitio de repositorios de templates lo compramos.
Cualquier cosa antes que empezar desde cero porque no vamos a llegar con
los tiempos.

2014-05-08 14:59 GMT-03:00 Federico Arena notifications@github.com:

> oka, buenisimo. Sigo buscando entonces, en esos dos sitios
> 
> ## 
> 
> Federico Arena
> Diseño & Desarrollo Web
> C: +54 11 15.6582.2442
> 
> http://faareia.com/
> http://faareia.com/
> 
> El 8 de mayo de 2014, 14:10, LeandroBraiernotifications@github.comescribió:
> 
> > No te centres tanto en hamburguesa en sí, sino en cosas que pueden ser
> > distintas pero la estética pegue. Pueden ser panchos, comida rápida,
> > gaseosas como 7up etc. Los colores principales de Paty son el rojo y el
> > blanco., tené en cuenta eso si querés, pero es más importante para la
> > estética el que esté apuntado a grupos de amigos, jovenes, juntadas,
> > etc,
> > que el hecho de que el producto sea un hamburguesa, entendés?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42577285>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42583226
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Tenes tiempo para un skype?

**Comment by LeandroBraier** [comment]
Ahora estamos entrando a reunión. Cuando salgo te aviso y salimos

abrazo

2014-05-08 15:45 GMT-03:00 Federico Arena notifications@github.com:

> Tenes tiempo para un skype?
> 
> El 8 de mayo de 2014, 15:36, LeandroBraiernotifications@github.comescribió:
> 
> > O en otros sitios de templates, no te restrinjas solo a ese. Si
> > encontrás
> > uno bueno en otro sitio de repositorios de templates lo compramos.
> > Cualquier cosa antes que empezar desde cero porque no vamos a llegar con
> > los tiempos.
> > 
> > 2014-05-08 14:59 GMT-03:00 Federico Arena notifications@github.com:
> > 
> > > oka, buenisimo. Sigo buscando entonces, en esos dos sitios
> > > 
> > > ## 
> > > 
> > > Federico Arena
> > > Diseño & Desarrollo Web
> > > C: +54 11 15.6582.2442
> > > 
> > > http://faareia.com/
> > > http://faareia.com/
> > > 
> > > El 8 de mayo de 2014, 14:10, LeandroBraiernotifications@github.comescribió:
> > > 
> > > > No te centres tanto en hamburguesa en sí, sino en cosas que pueden
> > > > ser
> > > > distintas pero la estética pegue. Pueden ser panchos, comida rápida,
> > > > gaseosas como 7up etc. Los colores principales de Paty son el rojo y
> > > > el
> > > > blanco., tené en cuenta eso si querés, pero es más importante para
> > > > la
> > > > estética el que esté apuntado a grupos de amigos, jovenes, juntadas,
> > > > etc,
> > > > que el hecho de que el producto sea un hamburguesa, entendés?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42577285>
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42583226>
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42587747>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42589060
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
okaaaaaa

**Comment by LeandroBraier** [comment]
Fede, ya estoy en skype hasta las 19 que salimos de vuelta.

2014-05-08 15:48 GMT-03:00 Federico Arena notifications@github.com:

> okaaaaaa
> 
> El 8 de mayo de 2014, 15:47, LeandroBraiernotifications@github.comescribió:
> 
> > Ahora estamos entrando a reunión. Cuando salgo te aviso y salimos
> > 
> > abrazo
> > 
> > 2014-05-08 15:45 GMT-03:00 Federico Arena notifications@github.com:
> > 
> > > Tenes tiempo para un skype?
> > > 
> > > El 8 de mayo de 2014, 15:36, LeandroBraiernotifications@github.comescribió:
> > > 
> > > > O en otros sitios de templates, no te restrinjas solo a ese. Si
> > > > encontrás
> > > > uno bueno en otro sitio de repositorios de templates lo compramos.
> > > > Cualquier cosa antes que empezar desde cero porque no vamos a llegar
> > > > con
> > > > los tiempos.
> > > > 
> > > > 2014-05-08 14:59 GMT-03:00 Federico Arena notifications@github.com:
> > > > 
> > > > > oka, buenisimo. Sigo buscando entonces, en esos dos sitios
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Federico Arena
> > > > > Diseño & Desarrollo Web
> > > > > C: +54 11 15.6582.2442
> > > > > 
> > > > > http://faareia.com/
> > > > > http://faareia.com/
> > > > > 
> > > > > El 8 de mayo de 2014, 14:10, LeandroBraier<
> > > > > notifications@github.com>escribió:
> > > > > 
> > > > > > No te centres tanto en hamburguesa en sí, sino en cosas que
> > > > > > pueden
> > > > > > ser
> > > > > > distintas pero la estética pegue. Pueden ser panchos, comida
> > > > > > rápida,
> > > > > > gaseosas como 7up etc. Los colores principales de Paty son el
> > > > > > rojo
> > > > > > y
> > > > > > el
> > > > > > blanco., tené en cuenta eso si querés, pero es más importante
> > > > > > para
> > > > > > la
> > > > > > estética el que esté apuntado a grupos de amigos, jovenes,
> > > > > > juntadas,
> > > > > > etc,
> > > > > > que el hecho de que el producto sea un hamburguesa, entendés?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42577285>
> > > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42583226>
> > > > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Leandro Braier
> > > > Producción Audiovisual & Social Media
> > > > Benteveo Producciones http://benteveo.tv
> > > > Móvil 1158717399
> > > > 
> > > > —
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > 
> > > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42587747>
> > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42589060>
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42589317>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/1#issuecomment-42589469
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
