### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#10]
MK, necesitamos un preloader para Paty, con una animación a definirse.

Cuando lo tengas pasaselo a Fede.

**Comment by mkreyness** [comment]
```
no se nada de preloaders, eso en el caso de las fotitos de
Experiencia Danica lo puso directamente Fede, ni idea de donde
salio.El 25/06/2014 11:09, LeandroBraier
  escribió:

  MK, necesitamos un preloader para Paty, con una animación a
    definirse.
  Cuando lo tengas pasaselo a Fede.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Fede, es para vos entonces.

**Comment by FAAREIA** [comment]
En realidad es distinto. En amamoscocinarconvos, es un plugin que carga las img visibles en pantalla, y las que vayan apareciendo a medida que se hace scroll. Después también sé como precargar imagenes puestas como backgrounds en el CSS, pero este caso es diferente. Habría que precargar las imágenes del home (son 19 y lo otro es un simple fondo), los scripts y recien ahi cargar todo el sitio.

**Comment by mkreyness** [comment]
```
Si queres me pongo a investigar como se hace, pero no tengo
experiencia con preloaders.El 25/06/2014 11:33, Federico Arena
  escribió:

  En realidad es distinto. En amamoscocinarconvos, es un plugin
    que carga las img visibles en pantalla, y las que vayan
    apareciendo a medida que se hace scroll. Después también sé como
    precargar imagenes puestas como backgrounds en el CSS, pero este
    caso es diferente. Habría que precargar las imágenes del home
    (son 19 y lo otro es un simple fondo), los scripts y recien ahi
    cargar todo el sitio.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Te diria de hacerlo yo marce, pero lo que siempre hice fueron cosas simples. Este caso lo veo más complejo ya que habría que ocultar el sitio hasta que se complete.

**Comment by mkreyness** [comment]
```
se te ocurre alguna pagina que funcione asi, para espiar como lo
hacen ?El 25/06/2014 11:40, Federico Arena
  escribió:

  Te diria de hacerlo yo marce, pero lo que siempre hice fueron
    cosas simples. Este caso lo veo más complejo ya que habría que
    ocultar el sitio hasta que se complete.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Capas que puedan servir estas dos:
http://edbangerroom.com/home
http://runbetter.newtonrunning.com/

**Comment by LeandroBraier** [comment]
Me gusta el de EdBanger. El otro no funciona bien.

On Wed, Jun 25, 2014 at 11:54 AM, Federico Arena notifications@github.com
wrote:

> Capas que puedan servir estas dos:
> http://edbangerroom.com/home
> http://runbetter.newtonrunning.com/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/10#issuecomment-47111842
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
EdBanger es un sitio completamente en Flash, no estamos trabajando con 
flash.
El otro a mi me anda, pero si decis que no te funciona, mejor ni me fijo.
Fede: encontre esta library, te parece que servira ?

http://thinkpixellab.com/pxloader/

**Comment by FAAREIA** [comment]
Por lo que lei tiene muy buena pinta. Solo usariamos lo de imagen nomás.

**Comment by mkreyness** [comment]
Podes instalarlo directamente vos o necesitas que yo haga algo ?

**Comment by FAAREIA** [comment]
lo pongo en la lista asi lo veo. Cualquier cosa te chiflo

**Comment by FAAREIA** [comment]
Hola Marce, estuve viendo el plugin pero lo leo y la verdad es que hay cosas que no las capto. Podrás verlo?

**Comment by mkreyness** [comment]
Lo pusiste en algun lado ?

**Comment by FAAREIA** [comment]
lo probé localmente y luego lo borre, no hay ningun residuo en lo que esta online

**Comment by mkreyness** [comment]
Es que no se como lo usarias, dejame alguna version en todo caso con un 
esbozo de como lo usarias asi veo que es lo que no funca.

**Comment by FAAREIA** [comment]
Es que no lo terminé de aplicar nunca, me quedé en el sample 1....
La idea de base puede ser llevar un div del 0% al 100% de ancho, junto con el número arriba. Al igual que lo hace 7up.

Otra cosa, la idea sería hacer el preloader hasta 768px de ancho, en resoluciones menores no porque no va a estar la animación.

**Comment by mkreyness** [comment]
miro despues a ver que es lo que hace 7up.
Un numero creciendo EN CADA foto ?

**Comment by FAAREIA** [comment]
Un número en el medio de la pantalla nomás, Después que aparezca el sitio, junto con la barra de scroll natural y todo su contenido.

**Comment by LeandroBraier** [comment]
Fede, esto quedó colocado? Yo nunca lo vi en ningún navegador.

**Comment by FAAREIA** [comment]
Hola Lea, lo podes ver en benteveo.tv/_paty7/index-precarga.html
Falta estilizarlo, pero precarga bien las imagenes iniciales de la animación.
Por otra parte, en que quedó lo de paty? Faltaría ajustar los responsivo.

**Comment by LeandroBraier** [comment]
La verdad no lo entiendo. Voy al link y me carga al toque, supongo que
tengo internet muy rápida. Lo voy a probar mañana desde la produ. Igual
andá estilizándolo porfa.

Respecto del sitio de Paty, andá avanzando con lo responsivo. Lo único que
puede pasar es que cambie una foto o dos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si, con una conección normal casi ni se ve, le voy a poner que cargue más cosas igual.

**Comment by marcsuse** [comment]
en mi maquina la animación inicial de  la home anda a los saltos

**Comment by FAAREIA** [comment]
Qué navegador estas usando Marce? Fijate primero desde index-precarga.html

**Comment by marcsuse** [comment]
safari mac

**Comment by LeandroBraier** [comment]
A mi en CHrome Versión 36.0.1985.125 no me aparece nada. Va captura
![captura de pantalla 2014-07-28 a la s 17 59 26](https://cloud.githubusercontent.com/assets/6719872/3727031/816a44a8-1699-11e4-9086-904b95ad1510.png)

**Comment by FAAREIA** [comment]
Hola Lea, estas cacheado. Ese texto ya no esta

## 

Federico Arena
Diseño & Desarrollo Web
C: +54 11 15.6582.2442

http://faareia.com/
http://faareia.com/

2014-07-28 17:55 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Ok, lo reloadeé pero veo otro texto pero no el preloader igualmente. Ya
está final entonces? Puede cerrar esta tarea?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-29 9:16 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si esta final

## 

Federico Arena
Diseño & Desarrollo Web
C: +54 11 15.6582.2442

http://faareia.com/
http://faareia.com/

**Comment by LeandroBraier** [comment]
Genial, terminado!

Pasame alguna captura o algo donde lo pueda ver cómo quedó así cierro el ticket.

abrazo

**Comment by FAAREIA** [comment]
Dale F5 o ctrl F5 apenas pones la url que es: http://benteveo.tv/_paty8/
Ahi lo podes ver en vivo, con una captura va a quedar muy estatico

2014-07-29 12:06 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Ya lo vi. Me funcionó bien en varios navegadores y conexiones lentas. Es simple pero funciona. Por ahora dejémoslo así. 

Más allá de esto, hay posibilidad de que se vea algo más que el Logo de Paty sobre fondo blanco? Algo más creativo? Un gif animado, algo.

**Comment by FAAREIA** [comment]
Pruebo de agregarle algunos chirimbolos que no sumen mucho peso ya que es
un preloader

**Comment by LeandroBraier** [comment]
Es cierto. Dejemoslo así por ahora. El de 7up es igual pero verde y ni siquiera muestra el logo, así que dejémoslo así está perfecto.

Gracias!
