### ISSUE TITLE
Fotos loading

### ISSUE THREAD

**Issue by FAAREIA** [LeandroBraier/PatyWeb#12]
Abro issue para las fotos.
Lo enviado esta OK, pero yo tengo un archivo diferente por imagen. Para hacerlo sobre lo enviado, tendría que recortar, escalar y rotar 28 fotos. Creo que sería mejor hacer ese laburo sobre imágenes ya definidas, o sino necesitaría las fotos sin rotar y sin escalar, las originales.

**Comment by LeandroBraier** [comment]
Ok. No te preocupes. Decime el tamaño que necesitás tener y te las preparo,
yo ya tengo las definitivas. Les pongo los números que vos usaste en la
maquetación actual.

¿Lo de recortar, escalar y demás no lo hace Java directamente?

2014-06-25 17:33 GMT-03:00 Federico Arena notifications@github.com:

> Abro issue para las fotos.
> Lo enviado esta OK, pero yo tengo un archivo diferente por imagen. Para
> hacerlo sobre lo enviado, tendría que recortar, escalar y rotar 28 fotos.
> Creo que sería mejor hacer ese laburo sobre imágenes ya definidas, o sino
> necesitaría las fotos sin rotar y sin escalar, las originales.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/12.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Vos pasamelas que yo las encajo en los polaroids que armé. Si el polaroid tiene frase, decime también. El tema es que las img no esten rotadas o dentro de polaroids.

**Comment by LeandroBraier** [comment]
ah, perfecto. Te paso lo que tengo, manteniendo los mismos nombres que las
otras.

https://www.wetransfer.com/downloads/f09bea3df9f7887fb19fa847a77f157520140625182732/e89fa110d7b9421be5814703d9bedc8b20140625182732/055450

2014-06-25 17:41 GMT-03:00 Federico Arena notifications@github.com:

> Vos pasamelas que yo las encajo en los polaroids que armé. Si tiene el
> polaroid tiene frase, decime también. El tema es que las img no esten
> rotadas o dentro de polaroids.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/12#issuecomment-47155770
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, ya tenemos las fotos nuevas!! Te las paso por Gmail.

Cambios:

A. la foto 2 al lugar 18

B. la foto 1 va al lugar 2

C. en la foto 1 va la IMG_7452-recortada.png (adjunta por gmail)

D. abajo va la frase: "Paty con amigos" en lugar de "Paty playero"

E. la foto 24 va al lugar 15

F. la foto IMG_7406 (adjunta por gmail) va al lugar de la 24

abrazo

Actualizado por última vez el 14/07/14 a las 11.40 am.

**Comment by LeandroBraier** [comment]
Fede, cambios en los pedidos. Te lo modifico directamente sobre el ticket anterior. abrazo
