### ISSUE TITLE
Pedir Hosting para el sitio de Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#13]
Alguien pidio el hosting para Paty ?

**Comment by LeandroBraier** [comment]
Fede, tengo el OK de Marce Susevich para solicitar un hosting para el sitio
de Paty. Me dijo que vos lo gestionabas. 

Cuando tengas el hosting avisame y consulto con el webmaster actual a donde
tiene que delegar la URL de Nic.Ar

Su mail es:

Matias.Parente@groupm.com

abrazo

**Comment by FAAREIA** [comment]
Pido un hosting que sobre un poco por si metemos el sitio de patyviena ahi.

Abrazo

**Comment by LeandroBraier** [comment]
Excelente idea.

abrazo

**Comment by LeandroBraier** [comment]
Fede, el hosting que necesitamos es el Apps S?

http://www.duplika.com/planes-web-hosting/compartidos

Confirmame esto y lo gestiono.

abrazo

**Comment by FAAREIA** [comment]
Si, con ese esta bien para paty y patyviena

2014-07-10 10:24 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Ya lo pedí, te aviso cuando lo tenga.

**Comment by LeandroBraier** [comment]
Gracias Fede! Cuando tengamos el sitio listo para publicar entonces le pido a 

Matias.Parente@groupm.com

que delegue el dominio a:

ns1.duplika.com / 199.102.230.88
ns2.duplika.com / 50.28.56.141

abrazo

**Comment by FAAREIA** [comment]
exacto
