### ISSUE TITLE
Favicon Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#14]
Fede, necesito que armes el Favicon de Paty.

**Comment by FAAREIA** [comment]
Hola Lea, fijate en _paty8 que ya lo subí.

**Comment by LeandroBraier** [comment]
Simplifiquemoslo más. Fondo transparent, sin líneas abajo, sin el texto de Paty. Solo la vaquita roja en el tamaño máximo que se pueda lograr. Creo que va a quedar bien.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_favicons/paty.html
Es el tamaño máximo, sin las lineas inferior que restarían ancho a la vaca. Para mi quedó bien, el tema es ver si ellos quieren poner su maca asi.

**Comment by LeandroBraier** [comment]
Es cierto, Fede. Está bueno, pero haceme una segunda opción igual pero
donde sí se vean las letras de Paty dentro de la vaca. Con eso estamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-29 12:59 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi va la opción 2.
http://www.benteveo.tv/_favicons/paty2.html

**Comment by LeandroBraier** [comment]
Confirmado: queda la opción 1, pero también tiene cositas blancas
alrededor. Si me pasás el PSD lo corrijo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Te paso los 2, pero lo que debes estar notando es el "halo". Los favicons
no se si pueden ser de 24bits transparente, por eso lo puse como 8bits y
transparente en pixeles donde no hay nada, y en pixeles con opacidad un
color de fondo (eso es el halo).

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_favicons/paty3.html
fijate ahi lea, estuve leyendo un toque y creo que no hay problemas con png 24bits

**Comment by LeandroBraier** [comment]
Los bordes quedaron perfectos, pero me sigo quedando con la versión que no
dice Paty. Solo la vaquita. Vamos con esa.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi lo subí Lea, acordate de darle F5 y que aun asi el navegador puede optar por lo actualizarlo al instante
