### ISSUE TITLE
Hosting Patyviena

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#15]
Fede, cuando tengamos listo el sitio de PatyViena, a qué dominios le pido que delegue Patyviena?

Ellos tienen registrado el patyviena.com.ar

Para Paty me habías dicho que delegue el dominio a:

ns1.duplika.com / 199.102.230.88
ns2.duplika.com / 50.28.56.141

Espero estos datos pero para PatyViena

abrazo

**Comment by FAAREIA** [comment]
Si, a esos DNS esta bien. Marce K luego hace una magia y lo hace funcionar en el mismo server. Le voy a peguntar bien como es asi también lo aprendo.

**Comment by mkreyness** [comment]
```
Aca esta la magia:
danicase@onyx2 [~/www]# cat index.cgi
#!/usr/bin/perl
use cPanelUserConfig;
use CGI ;
my $cgi = new CGI ;
if ($ENV{SERVER_NAME} =~ /amamoscocinarconvos/)
        {
        print $cgi->redirect("/exp/landing.html") ;
        }
else
        {
        print $cgi->redirect("http://www.danica.com.ar/danica") ;
        }
solo hay que agregarle los redirects a la pagina principal de cada
dominio que se vaya agregando.
Entonces todo va a ir al mismo server de Danica ?El 11/08/2014 10:51, Federico Arena
  escribió:

  Si, a esos DNS esta bien. Marce K luego hace una magia y lo
    hace funcionar en el mismo server. Le voy a peguntar bien como
    es asi también lo aprendo.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Marce, el server es Duplika pero es otro plan de hosting.
¿El archivo donde lo debería de poner?
¿Hay que tocar alguna configuración del perl?

**Comment by mkreyness** [comment]
Lo tenes que poner en el DocumentRoot (public_html , www, o como se 
llame) en vez de un index.html
Cualquier cosa que se llame "index" si hay una sola, el apache la 
levanta. Al llamarse .cgi se supone que lo abre para ejecutar y mira la 
primera linea y sabe que lo tiene que interpretar con Perl.
Es importante el tema permisos: tiene que tener permiso de ejecucion y 
lectura para el grupo.
El mio esta asi: -rwxrwxr-x

El modulo que usa "use cPanelUserConfig;" es un requisito de Duplika. Si 
no no encuentra las cosas y da error.
Deberia existir si o si porque es algo de ellos.
El modulo "use CGI;" deberia venir standard, si no hay que agregarla via 
cpanel (en la parte de instalacion de modulos Perl).

De la configuracion del apache no podemos tocar nada creo, al menos no 
veo que haya un archivo httpd.conf
