### ISSUE TITLE
Duplika no responde

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#16]
Fede, la gente de Duplika no responde. Moverías con tus contactos ahí aver si nos responden? 

Ya les mandé como 3 mails sumando el de ayer. Lo hablarías con ellos?

**Comment by FAAREIA** [comment]
A veces tardan 24hs en responder, ahi vi que te respondieron igual.

2014-09-18 17:18 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by mkreyness** [comment]
Fede,

Pude entrar pero no puedo hacer correr los scripts via web (a mano por 
ssh andan perfecto, pero no sirve de mucho).
Esto:

www.paty.com.ar/cgi-bin/test.pl

que deberia mostrarme el nombre del dominio, da error.

El error log NO MUESTRA que problema hay (si llamo a algo inexistente 
si, aparece en el error log, pero si llamo a lo existente, da error 500 
pero NO lo pone en el log).

El mismo exacto programa en danica.com.ar anda bien:

www.danica.com.ar/cgi-bin/test.pl

Seguramente la gente de soporte de duplika pueda encontrar mejor que yo 
que es lo que esta pasando...

**Comment by LeandroBraier** [comment]
Si, genial!

Dicen que ya hicieron lo de SSh. Ahora hay que preguntarle el tema de la lentitud del server.

**Comment by mkreyness** [comment]
Ojo igual por mucho que puedo entrar, no puedo hacer andar los scripts 
via web, ver mi otro mail.

**Comment by FAAREIA** [comment]
Sacaste los redirect del panel de control?
Ahora los voy a sacar y probamos, los archivos tuyos siguen ahi no?

**Comment by mkreyness** [comment]
Si, mis archivos siguen ahi, pero no corren, dan error.

**Comment by FAAREIA** [comment]
Ahi le saque la redirección y el alias a ver si toma lo tuyo

**Comment by mkreyness** [comment]
Es que es un tema totalmente independiente de las redirecciones, fijate 
que la prueba que mando NO es el index.cgi, es un /cgi-bin/test.pl, que 
en Danica anda perfecto y en Paty ni a palos. Lo que no esta habilitado 
es que se pueda correr perl desde web. Hay que avisarle a los de duplika.

Ademas la redireccion me sigue andando, si pones http://www.patyviena.com.ar
Si pongo http://pativiena.com.ar pincha con el SORRY.

**Comment by FAAREIA** [comment]
Marce, mandales un mail a info@duplika.com o sino pasame la descripción de
lo que se necesita y se los paso.

**Comment by mkreyness** [comment]
Ok, mando yo, copiandote.

**Comment by mkreyness** [comment]
Fede: Ya hicieron algo y corren los scripts.
Creo que le sacaron un permiso de escritura a mi script de prueba (que 
en Danica parece que no hacia falta, porque ahi lo sigue teniendo). La 
cuestion es que imité lo mismo con el index.cgi y correr, corre.
Ahora sí el tema es que saques el redireccionamiento de alias a ver que 
pasa.

**Comment by LeandroBraier** [comment]
Genial MK!

Probemos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-19 21:15 GMT-03:00 mkreyness notifications@github.com:

> Fede: Ya hicieron algo y corren los scripts.
> Creo que le sacaron un permiso de escritura a mi script de prueba (que
> en Danica parece que no hacia falta, porque ahi lo sigue teniendo). La
> cuestion es que imité lo mismo con el index.cgi y correr, corre.
> Ahora sí el tema es que saques el redireccionamiento de alias a ver que
> pasa.
> 
> El 19/09/2014 14:36, Federico Arena escribió:
> 
> > Marce, mandales un mail a info@duplika.com o sino pasame la descripción
> > de
> > lo que se necesita y se los paso.
> > 
> > El 19 de septiembre de 2014, 12:53, mkreynessnotifications@github.com
> > escribió:
> > 
> > > Es que es un tema totalmente independiente de las redirecciones, fijate
> > > que la prueba que mando NO es el index.cgi, es un /cgi-bin/test.pl, que
> > > en Danica anda perfecto y en Paty ni a palos. Lo que no esta habilitado
> > > es que se pueda correr perl desde web. Hay que avisarle a los de
> > > duplika.
> > > 
> > > Ademas la redireccion me sigue andando, si pones
> > > http://www.patyviena.com.ar
> > > Si pongo http://pativiena.com.ar pincha con el SORRY.
> > > 
> > > On 19/09/2014 12:24 p.m., Federico Arena wrote:
> > > 
> > > > Ahi le saque la redirección y el alias a ver si toma lo tuyo
> > > > 
> > > > El 19 de septiembre de 2014, 12:17, mkreyness<notifications@github.com
> > > > 
> > > > escribió:
> > > > 
> > > > > Si, mis archivos siguen ahi, pero no corren, dan error.
> > > > > 
> > > > > On 19/09/2014 10:39 a.m., Federico Arena wrote:
> > > > > 
> > > > > > Sacaste los redirect del panel de control?
> > > > > > Ahora los voy a sacar y probamos, los archivos tuyos siguen ahi no?
> > > > > > 
> > > > > > El 19 de septiembre de 2014, 0:00,
> > > > > > mkreynessnotifications@github.com
> > > > > > escribió:
> > > > > > 
> > > > > > > Ojo igual por mucho que puedo entrar, no puedo hacer andar los
> > > > > > > scripts
> > > > > > > via web, ver mi otro mail.
> > > > > > > 
> > > > > > > El 18/09/2014 23:48, LeandroBraier escribió:
> > > > > > > 
> > > > > > > > Si, genial!
> > > > > > > > 
> > > > > > > > Dicen que ya hicieron lo de SSh. Ahora hay que preguntarle el
> > > > > > > > tema
> > > > > > > > de la
> > > > > > > > lentitud del server.

**Comment by FAAREIA** [comment]
Ahi esta aplicado y anda, lo único que no veo y capas que nunca fue asi, es
que la url no queda enmascarada u oculta, sino que va al directorio
/patyviena/

**Comment by mkreyness** [comment]
Si, es inevitable.
En www.danica.com.ar tambien te lleva a www.danica.com.ar/danica
y en www.amamoscocinarconvos.com te lleva a una pagina especifica:
http://www.amamoscocinarconvos.com/exp/landing.html

Pero te muestra www.patyviena.com.ar/patyviena ?
Porque a mi me sigue mostrando www.paty.com.ar/patyviena

**Comment by LeandroBraier** [comment]
Exacto.

El problema principal es que si pongo:

http://patyviena.com.ar/

No me lleva a ningún lado.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-20 13:12 GMT-03:00 mkreyness notifications@github.com:

> Si, es inevitable.
> En www.danica.com.ar tambien te lleva a www.danica.com.ar/danica
> y en www.amamoscocinarconvos.com te lleva a una pagina especifica:
> http://www.amamoscocinarconvos.com/exp/landing.html
> 
> Pero te muestra www.patyviena.com.ar/patyviena ?
> Porque a mi me sigue mostrando www.paty.com.ar/patyviena
> 
> On 20/09/2014 12:49 p.m., Federico Arena wrote:
> 
> > Ahi esta aplicado y anda, lo único que no veo y capas que nunca fue
> > asi, es
> > que la url no queda enmascarada u oculta, sino que va al directorio
> > /patyviena/
> > 
> > El 19 de septiembre de 2014, 21:23,
> > LeandroBraiernotifications@github.com
> > escribió:
> > 
> > > Genial MK!
> > > 
> > > Probemos.
> > > 
> > > Leandro Braier
> > > Producción Audiovisual & Social Media
> > > Benteveo Producciones http://benteveo.tv
> > > Móvil 1158717399
> > > 
> > > 2014-09-19 21:15 GMT-03:00 mkreyness notifications@github.com:
> > > 
> > > > Fede: Ya hicieron algo y corren los scripts.
> > > > Creo que le sacaron un permiso de escritura a mi script de prueba
> > > > (que
> > > > en Danica parece que no hacia falta, porque ahi lo sigue
> > > > teniendo). La
> > > > cuestion es que imité lo mismo con el index.cgi y correr, corre.
> > > > Ahora sí el tema es que saques el redireccionamiento de alias a
> > > > ver que
> > > > pasa.
> > > > 
> > > > El 19/09/2014 14:36, Federico Arena escribió:
> > > > 
> > > > > Marce, mandales un mail a info@duplika.com o sino pasame la
> > > > > descripción
> > > > > de
> > > > > lo que se necesita y se los paso.
> > > > > 
> > > > > El 19 de septiembre de 2014, 12:53,
> > > > > mkreynessnotifications@github.com
> > > > > 
> > > > > escribió:
> > > > > 
> > > > > > Es que es un tema totalmente independiente de las redirecciones,
> > > > > > fijate
> > > > > > que la prueba que mando NO es el index.cgi, es un
> > > > > > /cgi-bin/test.pl,
> > > > > > que
> > > > > > en Danica anda perfecto y en Paty ni a palos. Lo que no esta
> > > > > > habilitado
> > > > > > es que se pueda correr perl desde web. Hay que avisarle a los de
> > > > > > duplika.
> > > > > > 
> > > > > > Ademas la redireccion me sigue andando, si pones
> > > > > > http://www.patyviena.com.ar
> > > > > > Si pongo http://pativiena.com.ar pincha con el SORRY.
> > > > > > 
> > > > > > On 19/09/2014 12:24 p.m., Federico Arena wrote:
> > > > > > 
> > > > > > > Ahi le saque la redirección y el alias a ver si toma lo tuyo
> > > > > > > 
> > > > > > > El 19 de septiembre de 2014, 12:17, mkreyness<
> > > > > > > notifications@github.com
> > > > > > > 
> > > > > > > escribió:
> > > > > > > 
> > > > > > > > Si, mis archivos siguen ahi, pero no corren, dan error.
> > > > > > > > 
> > > > > > > > On 19/09/2014 10:39 a.m., Federico Arena wrote:
> > > > > > > > 
> > > > > > > > > Sacaste los redirect del panel de control?
> > > > > > > > > Ahora los voy a sacar y probamos, los archivos tuyos siguen ahi
> > > > > > > > > no?
> > > > > > > > > 
> > > > > > > > > El 19 de septiembre de 2014, 0:00,
> > > > > > > > > mkreynessnotifications@github.com
> > > > > > > > > escribió:
> > > > > > > > > 
> > > > > > > > > > Ojo igual por mucho que puedo entrar, no puedo hacer andar los
> > > > > > > > > > scripts
> > > > > > > > > > via web, ver mi otro mail.
> > > > > > > > > > 
> > > > > > > > > > El 18/09/2014 23:48, LeandroBraier escribió:
> > > > > > > > > > 
> > > > > > > > > > > Si, genial!
> > > > > > > > > > > 
> > > > > > > > > > > Dicen que ya hicieron lo de SSh. Ahora hay que preguntarle el
> > > > > > > > > > > tema
> > > > > > > > > > > de la
> > > > > > > > > > > lentitud del server.

**Comment by mkreyness** [comment]
Entonces hay algun problema con donde apunta el alias, fijate como esta 
amamoscocinarconvos.com en el cPanel de Danica.Ambos tienen que apuntar 
al mismo directorio public_html, sin nada raro.

Fijate que si hago

http://patyviena.com.ar/cgi-bin/test.pl

da un error, mientras que si hago

http://paty.com.ar/cgi-bin/test.pl

me muestra el dominio (paty.com.ar).

La idea es que

http://patyviena.com.ar/cgi-bin/test.pl

deberia mostrar el dominio (patyviena.com.ar)

Mientras eso no ande, el redireccionamiento no va a poder funcionar.

**Comment by FAAREIA** [comment]
Debo estar cacheado en el ISP, porque "patyviena.com.ar" me lleva a
http://www.paty.com.ar/patyviena/
Si ustedes me dicen que "patyviena.com.ar" no lleva a ningun lado, agrego
nuevamente la redirección

**Comment by mkreyness** [comment]
Renicie mi maquina y ahora patyviena.com.ar directamente no lo encuentra 
como dominio.

Probé desde un host que tengo afuera y da "host not found".
Los DNS estan bien, apuntan a duplika.com

Hay algun lio con eso de los alias en el propio hosting.

**Comment by mkreyness** [comment]
Parece qu al sacar el alias se borró del todo el dominio de los DNS, por 
eso no responde o tiene cacheado cualquier cosa.
Ahi lo estoy volviendo a poner.

**Comment by FAAREIA** [comment]
no puede ser eso marce, nic.ar almaneca los DNS y esto es un CPanel en otro
server.

**Comment by mkreyness** [comment]
Sonamos, da error al tratar de volverlo a agregar:

There was a problem creating the alias. Lo siento el dominio ya esta 
apuntado a una dirección de IP que no parece estar usando los servidores 
de DNS asociados con este servidor. Por favor transfiera el dominio a 
estos servidores de nombre o digale a su administrador de sistemas que 
añada uno de los servidores de nombre a /etc/ips.remotedns y que crea 
las entradas tipo A en el servidor de nombre remoto.

Mandale esto a los de duplika a ver que pueden hacer.
Lo unico que queremos es que patyviena.com.ar apunte exactamente igual 
que paty.com.ar, que sean sinonimos.
El resto lo manejo yo con el index.cgi

**Comment by mkreyness** [comment]
No, nic.ar solo tiene los nombres de los DNS asociados al dominio, pero 
no tiene idea de los IP. Esa es justamente tarea del nameserver de la 
compañia de hosting.
En nuestro caso, Duplika tiene algun servidor donde fisicamente corre un 
programa que se llama BIND o similares, que se encarga de resolver la 
relacion domain->ip.
Ese es el eslabón que se rompió.

**Comment by FAAREIA** [comment]
Se lo mando, pero no me termina de cerrar, creo que el index.cgi es el que
impide ponerlo otra vez. Antes se podía, ahora que funciona ese archivo no.
Copio y pego lo que pusiste en el mail

**Comment by mkreyness** [comment]
Renombra el index.cgi como mas te guste, nunca llega a el, ni a ninguna 
otra cosa, porque patyviena.com.ar desaparecio del universo !

Mira, lo hago desde un servidor de Amazon donde trabajo habitualmente:

# host patyviena.com.ar

Host patyviena.com.ar not found: 3(NXDOMAIN)

En cambio si lo hago con paty.com.ar:

# host paty.com.ar

paty.com.ar has address 67.225.221.23
paty.com.ar mail is handled by 0 paty.com.ar.

Esto es porque patyviena.com.ar no esta cargado en el DNS que dice 
estar. Se borro al eliminar el alias, y lo malo es que no me lo deja 
volver a poner.

Proba cualquiera de esos servicios online que chequean DNS, vas a ver 
que esta todo mal.

**Comment by FAAREIA** [comment]
Ahi lo pinguié y no esta =/

**Comment by marcsuse** [comment]
El problema es que el DNS de duplika no lo esta resolviendo

CHMini:~ L$ dig any patyviena.com.ar +trace +all

; <<>> DiG 9.8.3-P1 <<>> any patyviena.com.ar +trace +all
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46299
;; flags: qr ra; QUERY: 1, ANSWER: 13, AUTHORITY: 0, ADDITIONAL: 15

;; QUESTION SECTION:
;.              IN  NS

;; ANSWER SECTION:
.           141819  IN  NS  h.root-servers.net.
.           141819  IN  NS  i.root-servers.net.
.           141819  IN  NS  j.root-servers.net.
.           141819  IN  NS  k.root-servers.net.
.           141819  IN  NS  l.root-servers.net.
.           141819  IN  NS  m.root-servers.net.
.           141819  IN  NS  a.root-servers.net.
.           141819  IN  NS  b.root-servers.net.
.           141819  IN  NS  c.root-servers.net.
.           141819  IN  NS  d.root-servers.net.
.           141819  IN  NS  e.root-servers.net.
.           141819  IN  NS  f.root-servers.net.
.           141819  IN  NS  g.root-servers.net.

;; ADDITIONAL SECTION:
i.root-servers.net. 604749  IN  A   192.36.148.17
j.root-servers.net. 604749  IN  A   192.58.128.30
k.root-servers.net. 604749  IN  A   193.0.14.129
l.root-servers.net. 604750  IN  A   199.7.83.42
m.root-servers.net. 228226  IN  A   202.12.27.33
m.root-servers.net. 256795  IN  AAAA    2001:dc3::35
a.root-servers.net. 228215  IN  A   198.41.0.4
a.root-servers.net. 236897  IN  AAAA    2001:503:ba3e::2:30
b.root-servers.net. 604228  IN  A   192.228.79.201
c.root-servers.net. 604746  IN  A   192.33.4.12
d.root-servers.net. 604437  IN  A   199.7.91.13
e.root-servers.net. 604437  IN  A   192.203.230.10
f.root-servers.net. 604437  IN  A   192.5.5.241
g.root-servers.net. 604438  IN  A   192.112.36.4
h.root-servers.net. 604438  IN  A   128.63.2.53

;; Query time: 318 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Sat Sep 20 20:05:24 2014
;; MSG SIZE  rcvd: 492

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58187
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 7, ADDITIONAL: 11

;; QUESTION SECTION:
;patyviena.com.ar.      IN  ANY

;; AUTHORITY SECTION:
ar.         172800  IN  NS  ar.cctld.authdns.ripe.net.
ar.         172800  IN  NS  ctina.ar.
ar.         172800  IN  NS  athea.ar.
ar.         172800  IN  NS  c.dns.ar.
ar.         172800  IN  NS  ns2.switch.ch.
ar.         172800  IN  NS  relay1.mecon.gov.ar.
ar.         172800  IN  NS  a.dns.ar.

;; ADDITIONAL SECTION:
a.dns.ar.       172800  IN  A   200.108.145.50
c.dns.ar.       172800  IN  A   200.108.148.50
ar.cctld.authdns.ripe.net. 172800 IN    A   193.0.9.59
ns2.switch.ch.      172800  IN  A   130.59.138.49
athea.ar.       172800  IN  A   200.16.98.2
ctina.ar.       172800  IN  A   200.16.97.17
relay1.mecon.gov.ar.    172800  IN  A   168.101.16.10
a.dns.ar.       172800  IN  AAAA    2801:140::10
c.dns.ar.       172800  IN  AAAA    2801:140:10::10
ar.cctld.authdns.ripe.net. 172800 IN    AAAA    2001:67c:e0::59
ns2.switch.ch.      172800  IN  AAAA    2001:620::1b:5054:ff:fe74:8780

;; Query time: 3894 msec
;; SERVER: 192.112.36.4#53(192.112.36.4)
;; WHEN: Sat Sep 20 20:05:28 2014
;; MSG SIZE  rcvd: 431

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58396
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;patyviena.com.ar.      IN  ANY

;; AUTHORITY SECTION:
patyviena.com.ar.   3600    IN  NS  ns2.duplika.com.
patyviena.com.ar.   3600    IN  NS  ns1.duplika.com.

;; ADDITIONAL SECTION:
ns1.duplika.com.    9325    IN  A   179.43.126.123
ns2.duplika.com.    9325    IN  A   50.28.56.141

;; Query time: 339 msec
;; SERVER: 168.101.16.10#53(168.101.16.10)
;; WHEN: Sat Sep 20 20:05:28 2014
;; MSG SIZE  rcvd: 113

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 41606
;; flags: qr; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;patyviena.com.ar.      IN  ANY

;; Query time: 188 msec
;; SERVER: 50.28.56.141#53(50.28.56.141)
;; WHEN: Sat Sep 20 20:05:28 2014
;; MSG SIZE  rcvd: 34

**Comment by mkreyness** [comment]
Si, yo tambien hice esas pruebas.
Al borrar el alias desde el CPanel lo borraron del DNS, pero al tratar 
de reponer el alias da este error:

There was a problem creating the alias. Lo siento el dominio ya esta
apuntado a una dirección de IP que no parece estar usando los
servidores de DNS asociados con este servidor. Por favor transfiera el dominio a
estos servidores de nombre o digale a su administrador de sistemas que
añada uno de los servidores de nombre a /etc/ips.remotedns y que crea
las entradas tipo A en el servidor de nombre remoto.

Fede ya les mando mail.

**Comment by FAAREIA** [comment]
Ahi ya pude resetear la Zona de DNS, estaba en el CPanel la opción. El tema
es que aún no funciona el script

**Comment by mkreyness** [comment]
El script funciona, si se lo llama explicitamente:

www.patyviena.com.ar/index.cgi

pero no lo llama por default, como si funcionaba sin problemas en 
danica.com.ar
Estoy viendo que diferencia puede haber.

**Comment by mkreyness** [comment]
Ahhh, sigue estando el redireccionamiento automatico, mientras no se 
saque eso nunca va a llamar a mi script.
Ahi lo saque, pero sigue aplicado, no se cuanto puede tardar en dejar de 
existir, pero mientras exista no va a llamar nunca a lo mio.

**Comment by mkreyness** [comment]
El script index.cgi no era llamado nunca en forma autmatica porque 
existia un index.html que le ganaba en prioridad.
Ahi lo renombre y entra mi index.cgi, que en el caso de paty.com.ar 
redirecciona a paty.com.ar/home.html lo mas bien.
Probando desde afuera con patyviena.com.ar tambien me anda bien ahora, 
pero con mi browser hay algo cacheado, prueben ustedes por favor.

**Comment by mkreyness** [comment]
ah, el index.html era el que ponia el progress. Bueno, lo renombré como 
prehome.html e hice que el index.cgi apunte ahi.
