### ISSUE TITLE
Incorporar Link Información CNV

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#18]
Fede, necesitamos incorporar lo antes posible al sitio de Paty y Patyviena un link llamado "Información Financiera CNV" que lleve a esta URL: 

http://www.cnv.gob.ar/InfoFinan/emisoras.asp?Lang=0&CodiSoc=1090&DescriSoc=Quickfood%20S.A.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20&Letra=Q

Ubicalo al pie del formulario de contacto.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya lo puse en los 2

**Comment by LeandroBraier** [comment]
Perfecto!

Gracias Fede.
