### ISSUE TITLE
Pop Up Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#20]
Fede, te escribo para avisarte que todavía no está el OK para subir el pop up al sitio de Paty. Esperame que te confirme para avanzar porfa.

abrazo

**Comment by LeandroBraier** [comment]
Fede, no podemos usar vimeo para el pop up. Urgente hay que ir por la otra versión, mirá lo que le aparece a la gente de BRF al entrar en home2.html. Ellos tienen vimeo filtrado no sé por qué, creo que también youtube.

![bloqueo de url de vimeo](https://cloud.githubusercontent.com/assets/6719872/4882576/da14f232-6357-11e4-9d3e-9a8022d91c73.jpeg)

Urgente hagamos una nueva versión con el video actual (por ahora no hay indicios de que vaya a aparecer un nuevo archivo en HD).

abrazo

**Comment by FAAREIA** [comment]
Ok, lo convierto y lo meto como Video HTML5, pero IE8 no lo va a poder ver.

**Comment by LeandroBraier** [comment]
Vamos a estar en la misma, vos viste la captura. Esa es IE8, ¿no?

¿No podemos hacer que filtre a los IE8 y les muestre el video en algún otro
formato?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
No acepta formatos del video IE8, acepta youtube, vimeo, flash. Acordate que en las Landing de las marcas IE8 no se ve, hay un flash de fondo que se reproduce una vez y listo, no podes ni volver a verlo.

Creo que ellos tenian IE9. Igualmente este cambio solo serviría para que ellos lo puedan ver dentro de su empresa porque les bloquearon Vimeo. En condiciones normales lo podrían ver.

**Comment by LeandroBraier** [comment]
Si, entiendo yo eso. Pero andá a explicarselo a ellos!

Si ellos tiene IE9 estamos salvados entonces. Avisame cuando esté ya el
video nuevo así le aviso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-03 10:16 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
oka

**Comment by FAAREIA** [comment]
Ahi esta listo, para IE8 aún no hay video. Te aviso cuando se lo ponga.
Al final converti los videos sobre el .mp4 que me habías pasado y no el .mov. Tiene mejor calidad ahora, era bueno el mp4

**Comment by LeandroBraier** [comment]
Excelente Fede! Pero no me hace autorun en Chrome ni en Safari. En Firefox
si.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-03 11:41 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Fijate ahora

**Comment by LeandroBraier** [comment]
Sigue igual, sin Autorun en Chrome y Safari.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ok, ahi estoy probando pero no lo puedo hacer andar. Voy a seguir investigando

**Comment by FAAREIA** [comment]
Fijate ahora Lea, yo lo veo bien aca en Chrome.
Ya esta lo del SWF también, pesa como 4MB más que los otros.

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Ya lo paso al cliente y te confirmo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-03 13:06 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Confirmado Fede!

Subilo al sitio de Paty posta y avisame por favor.

Gracias!

**Comment by FAAREIA** [comment]
subido

**Comment by LeandroBraier** [comment]
Gracias Fede!
