### ISSUE TITLE
Agregar Novedad en la Web de Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#21]
Fede, ahora que tenés maquetadas las dos pantallas de Siguit, y una vez que hayas terminado con la tanda 6 de landings, necesito que subas este texto a la sección de "Novedades" de Paty. Ponelo a la izquierda de todo y quitá la que dice "Paty presente"

Título: ¡Paty quiere celebrar el año con vos!

Texto: Un camión inteligente arma la fiesta en dónde vos estés. Como en las grandes ciudades del mundo, Paty tiene un food track equipado con la última tecnología: wi-fi, dvd, luces y salones con todo el confort de un buen restaurante. ¡Que no se te pase!

Foto: te la dejé en PATY MAQUETADOR/ CAMION PATY. Recortala o adaptala como sea necesario.

abrazo

**Comment by FAAREIA** [comment]
http://www.paty.com.ar/home.html

Ahi en 10 salgo para allá
