### ISSUE TITLE
Accesos FTP a Sitios Danica y Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#22]
Marce y Fede: FInalmente estos hijos se nos van de casa. Tenemos que entregar los sitios de Paty y Dánica de nuevo a BRF, si bien tenemos para hacer la próxima campaña de Dánica no vamos a seguir comunicando redes ni modificando los sitios web de ellos.

Necesito si me pueden confirmar qie tengo bien los datos de acceso por FTP a Dánica y Paty (y si el de Paty incluye Patyviena).

ftp.danica.com.ar  
danicase  
7876mdrxYD

ftp.paty.com.ar 
patycoma  
d89Uje1zV5

Puerto FTPS explícito de FTP &:  21        

abrazo

**Comment by mkreyness** [comment]
```
Ok los FTP que pones abajo acabo de verificar que funcionan, salvo
que mientras no renueven el dominio, danica.com.ar no anda.
Tendrian que usar tambien "danica.servidoronline.net" (verificado
que funciona).

Igual no creo que les alcance con acceder FTP, salvo que solo
quieran bajarse todo y ponerlo en otro lado (hacer que funcione ya
es problema de ellos).

El 30/03/2015 a las 22:40,
  LeandroBraier escribió:


  Marce y Fede: FInalmente estos hijos se nos van de casa.
    Tenemos que entregar los sitios de Paty y Dánica de nuevo a BRF,
    si bien tenemos para hacer la próxima campaña de Dánica no vamos
    a seguir comunicando redes ni modificando los sitios web de
    ellos.
  Necesito si me pueden confirmar qie tengo bien los datos de
    acceso por FTP a Dánica y Paty (y si el de Paty incluye
    Patyviena).
  ftp.danica.com.ar

    danicase

    7876mdrxYD
  ftp.paty.com.ar 
    patycoma

    d89Uje1zV5
  Puerto FTPS explícito de FTP &: 21 
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Esos accesos también sirven para entrar por el puerto 2082 y acceder al panel de control.
danica.com.ar:2082
paty.com.ar:2082

**Comment by LeandroBraier** [comment]
Gracias Fede! Igual mi idea no era pasarles el acceso al panel de control
de los hostings, sino al FTP para que se bajen los materiales y nada más.
LO mismo que le pedimos al proveedor anterior de Klaukol.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-31 9:16 GMT-03:00 Federico Arena notifications@github.com:
