### ISSUE TITLE
Sistema de Asistente Dánica y Dánica App

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#23]
Marce, la gente de BRF me pide "el sistema" del Asistente Dánica y "el sistema" de la App Recetario Dánica.

Entiendo que se refieren a los archivos editables. Qué les debería dar?

abrazo

**Comment by mkreyness** [comment]
```
Asistente Danica:
Esta todo en el site cuyas llaves les estas entregando, la cagada es
que ahi tambien les va el CMS de regalo, lo cual mucha gracia no me
hace.
Hasta que punto hay que darles todo ? El CMS es un tool de uso
backoffice.

App:
Son las cosas que fui descargando del repositorio de los hindues.
Busco y te mando las ultimas versiones ? Son carpetas comprimidas.


El 30/03/2015 a las 22:43,
  LeandroBraier escribió:


  Marce, la gente de BRF me pide "el sistema" del Asistente
    Dánica y "el sistema" de la App Recetario Dánica.
  Entiendo que se refieren a los archivos editables. Qué les
    debería dar?
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by marcsuse** [comment]
Del App, los fuentes que nos mandaron los indios

del Asistente, es el codigo que corre en el server para armar los mails de acuerdo a la base de datos

MARCELO SUSEVICH
BENTEVEO
Guatemala 5582 - Piso 2 (CABA) Argentina
T. +54 11.52.54.73.63
E. marcelo@benteveo.tv
W. www.benteveo.tv

**Comment by marcsuse** [comment]
Tratemos de no darles el CMS

MARCELO SUSEVICH
BENTEVEO
Guatemala 5582 - Piso 2 (CABA) Argentina
T. +54 11.52.54.73.63
E. marcelo@benteveo.tv
W. www.benteveo.tv

**Comment by LeandroBraier** [comment]
Gracias a los dos!

Dale, MK, pasame la última versión por las dudas.

Respecto del CMS boto por no darselo también, pero en el casod e Dánica
desarmamos todo el sitio sin el CMS no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-30 22:50 GMT-03:00 marcsuse notifications@github.com:

> Tratemos de no darles el CMS
> 
> MARCELO SUSEVICH
> BENTEVEO
> Guatemala 5582 - Piso 2 (CABA) Argentina
> T. +54 11.52.54.73.63
> E. marcelo@benteveo.tv
> W. www.benteveo.tv
>

**Comment by mkreyness** [comment]
```
Puedo borrar el CMS entonces antes de que les pasen los datos de
acceso ?
El resto de los programas especificos de envio de los mailings y
todo eso sigue funcionando sin problema, lo que no van a tener es
como agregarle contenido salvo a mano en la base de datos.

El 30/03/2015 a las 22:50, marcsuse
  escribió:

Tratemos de no darles el CMS



  MARCELO SUSEVICH
  BENTEVEO
  Guatemala 5582 - Piso 2 (CABA) Argentina
  T. +54 11.52.54.73.63
  E. marcelo@benteveo.tv
  W. www.benteveo.tv

  On Mar 30, 2015, at 10:48 PM, mkreyness
  <notifications@github.com> wrote:

  > 
  > 
  > 
  > 
  > 
  > Asistente Danica:
  > Esta todo en el site cuyas llaves les estas entregando, la
  cagada es
  > que ahi tambien les va el CMS de regalo, lo cual mucha gracia
  no me
  > hace.
  > Hasta que punto hay que darles todo ? El CMS es un tool de
  uso
  > backoffice.
  > 
  > App:
  > Son las cosas que fui descargando del repositorio de los
  hindues.
  > Busco y te mando las ultimas versiones ? Son carpetas
  comprimidas.
  > 
  > 
  > El 30/03/2015 a las 22:43,
  > LeandroBraier escribió:
  > 
  > 
  > Marce, la gente de BRF me pide "el sistema" del Asistente
  > Dánica y "el sistema" de la App Recetario Dánica.
  > Entiendo que se refieren a los archivos editables. Qué les
  > debería dar?
  > abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  > —
  > Reply to this email directly or view it on GitHub.
  > 

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
El sitio va a seguir funcionando, pero no teniendo el "recetas.pl",
les va a ser medio cuesta arriba agregar/modificar recetas.
Te mando lo que tengo del App a tu casilla gmail.

El 30/03/2015 a las 22:55,
  LeandroBraier escribió:

Gracias a los dos!

  Dale, MK, pasame la última versión por las dudas.

  Respecto del CMS boto por no darselo también, pero en el casod e
  Dánica
  desarmamos todo el sitio sin el CMS no?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-03-30 22:50 GMT-03:00 marcsuse
  <notifications@github.com>:

  > Tratemos de no darles el CMS
  >
  >
  >
  > MARCELO SUSEVICH
  > BENTEVEO
  > Guatemala 5582 - Piso 2 (CABA) Argentina
  > T. +54 11.52.54.73.63
  > E. marcelo@benteveo.tv
  > W. www.benteveo.tv
  >
  > On Mar 30, 2015, at 10:48 PM, mkreyness
  <notifications@github.com> wrote:
  >
  > >
  > >
  > >
  > >
  > >
  > > Asistente Danica:
  > > Esta todo en el site cuyas llaves les estas entregando,
  la cagada es
  > > que ahi tambien les va el CMS de regalo, lo cual mucha
  gracia no me
  > > hace.
  > > Hasta que punto hay que darles todo ? El CMS es un tool
  de uso
  > > backoffice.
  > >
  > > App:
  > > Son las cosas que fui descargando del repositorio de los
  hindues.
  > > Busco y te mando las ultimas versiones ? Son carpetas
  comprimidas.
  > >
  > >
  > > El 30/03/2015 a las 22:43,
  > > LeandroBraier escribió:
  > >
  > >
  > > Marce, la gente de BRF me pide "el sistema" del
  Asistente
  > > Dánica y "el sistema" de la App Recetario Dánica.
  > > Entiendo que se refieren a los archivos editables. Qué
  les
  > > debería dar?
  > > abrazo
  > > —
  > > Reply to this email directly or view
  > > it on GitHub.
  > > —
  > > Reply to this email directly or view it on GitHub.
  > >
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/PatyWeb/issues/23#issuecomment-87896739
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Perfecto, MK. Me parece bien sacar el Recetas.Pl.

Cualquier cosa si nos dicen algo te aviso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-30 22:59 GMT-03:00 mkreyness notifications@github.com:

> El sitio va a seguir funcionando, pero no teniendo el "recetas.pl",
> les va a ser medio cuesta arriba agregar/modificar recetas.
> Te mando lo que tengo del App a tu casilla gmail.
> 
> El 30/03/2015 a las 22:55,
> LeandroBraier escribió:
> 
> Gracias a los dos!
> 
> Dale, MK, pasame la última versión por las dudas.
> 
> Respecto del CMS boto por no darselo también, pero en el casod e
> Dánica
> desarmamos todo el sitio sin el CMS no?
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> 2015-03-30 22:50 GMT-03:00 marcsuse
> notifications@github.com:
> 
> > Tratemos de no darles el CMS
> > 
> > MARCELO SUSEVICH
> > BENTEVEO
> > Guatemala 5582 - Piso 2 (CABA) Argentina
> > T. +54 11.52.54.73.63
> > E. marcelo@benteveo.tv
> > W. www.benteveo.tv
> > 
> > On Mar 30, 2015, at 10:48 PM, mkreyness

**Comment by mkreyness** [comment]
```
Listo ya borre todo lo del CMS.
Ademas me estoy haciendo backup de todo lo que nos pueda ser util
para otras cosas y borrando basura inutil (pruebas y temporarios
viejos).
A ellos les va a quedar todo funcionando.
Tambien esta el tema de la moderacion de facebook, que esta
vinculada al App que esta creado con mi usuario, eso no se como
delegarselos, pero supongo que hay que autorizar a quien se encargue
de moderar como ahora estas autorizado vos.

El 31/03/2015 a las 7:39, LeandroBraier
  escribió:

Perfecto, MK. Me parece bien sacar el Recetas.Pl.

  Cualquier cosa si nos dicen algo te aviso.

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-03-30 22:59 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > El sitio va a seguir funcionando, pero no teniendo el
  "recetas.pl",
  > les va a ser medio cuesta arriba agregar/modificar recetas.
  > Te mando lo que tengo del App a tu casilla gmail.
  >
  > El 30/03/2015 a las 22:55,
  > LeandroBraier escribió:
  >
  > Gracias a los dos!
  >
  > Dale, MK, pasame la última versión por las dudas.
  >
  > Respecto del CMS boto por no darselo también, pero en el
  casod e
  > Dánica
  > desarmamos todo el sitio sin el CMS no?
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-03-30 22:50 GMT-03:00 marcsuse
  > <notifications@github.com>:
  >
  > > Tratemos de no darles el CMS
  > >
  > >
  > >
  > > MARCELO SUSEVICH
  > > BENTEVEO
  > > Guatemala 5582 - Piso 2 (CABA) Argentina
  > > T. +54 11.52.54.73.63
  > > E. marcelo@benteveo.tv
  > > W. www.benteveo.tv
  > >
  > > On Mar 30, 2015, at 10:48 PM, mkreyness
  > <notifications@github.com> wrote:
  > >
  > > >
  > > >
  > > >
  > > >
  > > >
  > > > Asistente Danica:
  > > > Esta todo en el site cuyas llaves les estas
  entregando,
  > la cagada es
  > > > que ahi tambien les va el CMS de regalo, lo cual
  mucha
  > gracia no me
  > > > hace.
  > > > Hasta que punto hay que darles todo ? El CMS es un
  tool
  > de uso
  > > > backoffice.
  > > >
  > > > App:
  > > > Son las cosas que fui descargando del repositorio
  de los
  > hindues.
  > > > Busco y te mando las ultimas versiones ? Son
  carpetas
  > comprimidas.
  > > >
  > > >
  > > > El 30/03/2015 a las 22:43,
  > > > LeandroBraier escribió:
  > > >
  > > >
  > > > Marce, la gente de BRF me pide "el sistema" del
  > Asistente
  > > > Dánica y "el sistema" de la App Recetario Dánica.
  > > > Entiendo que se refieren a los archivos editables.
  Qué
  > les
  > > > debería dar?
  > > > abrazo
  > > > —
  > > > Reply to this email directly or view
  > > > it on GitHub.
  > > > —
  > > > Reply to this email directly or view it on GitHub.
  > > >
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > >
  >
```

https://github.com/LeandroBraier/PatyWeb/issues/23#issuecomment-87896739
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/PatyWeb/issues/23#issuecomment-87897867
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Grande Marce!!

No te preocupes por la moderación de Facebook. Yo les paso el admin desde
mi usuario.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-31 9:07 GMT-03:00 mkreyness notifications@github.com:

> Listo ya borre todo lo del CMS.
> Ademas me estoy haciendo backup de todo lo que nos pueda ser util
> para otras cosas y borrando basura inutil (pruebas y temporarios
> viejos).
> A ellos les va a quedar todo funcionando.
> Tambien esta el tema de la moderacion de facebook, que esta
> vinculada al App que esta creado con mi usuario, eso no se como
> delegarselos, pero supongo que hay que autorizar a quien se encargue
> de moderar como ahora estas autorizado vos.
> 
> El 31/03/2015 a las 7:39, LeandroBraier
> escribió:
> 
> Perfecto, MK. Me parece bien sacar el Recetas.Pl.
> 
> Cualquier cosa si nos dicen algo te aviso.
> 
> abrazo
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> 2015-03-30 22:59 GMT-03:00 mkreyness
> notifications@github.com:
> 
> > El sitio va a seguir funcionando, pero no teniendo el
> > "recetas.pl",
> > les va a ser medio cuesta arriba agregar/modificar recetas.
> > Te mando lo que tengo del App a tu casilla gmail.
> > 
> > El 30/03/2015 a las 22:55,
> > LeandroBraier escribió:
> > 
> > Gracias a los dos!
> > 
> > Dale, MK, pasame la última versión por las dudas.
> > 
> > Respecto del CMS boto por no darselo también, pero en el
> > casod e
> > Dánica
> > desarmamos todo el sitio sin el CMS no?
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > 2015-03-30 22:50 GMT-03:00 marcsuse
> > notifications@github.com:
> > 
> > > Tratemos de no darles el CMS
> > > 
> > > MARCELO SUSEVICH
> > > BENTEVEO
> > > Guatemala 5582 - Piso 2 (CABA) Argentina
> > > T. +54 11.52.54.73.63
> > > E. marcelo@benteveo.tv
> > > W. www.benteveo.tv
> > > 
> > > On Mar 30, 2015, at 10:48 PM, mkreyness
