### ISSUE TITLE
Consulta técnica de implementación

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#24]
@mkreyness podemos levantar los avatares de usuarios de un hashtag de twitter y posicionarlos dentro de una web en vivo?

**Comment by mkreyness** [comment]
Cuantos avatares querrias levantar ?
Por lo que estuve trabajando ayer, sin el API solo puedo acceder a un numero bastante limitado de tweets de un hashtag, no me aparece como paginar o mostrar mas.
"En vivo" significa estar permanenemente viendo si aparece alguno nuevo ?
Si no es para un uso supermasivo yo usaria el API, que trae muchisimos mas tweets por vez.

**Comment by LeandroBraier** [comment]
Serán 10 por vez máximo. Se puede entonces no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-21 13:55 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, ojo que muchas veces no son personas sino marcas, hay que ver si podemos diferenciarlos.

**Comment by LeandroBraier** [comment]
Si, no te preocupes por eso, vemos si nos aprueban esa propuesta. Te aviso.
