### ISSUE TITLE
Landing Paty Chile

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#25]
Brau, necesito que diseñes una landing bien minimalista y simple (podés tomar elementos de la estética del sitio de Paty) que tenga lo siguiente:

1) Que pida Facebook Connect apenas llegue para entrar.

2) Que diga: "Compartí la tradición de ser fiel a tu origen y ganá un 50% de descuento en un pack grande de Paty"

3) Abajo, que haya un botón de "Me gusta" de la página de Paty Chile

https://www.facebook.com/paty.chile

4) Que al lado del botón de Me gusta este el logo de Paty y debajo que diga "El sabor original" en tipografía de MetaPlus.

5) Que al hacer clic en "Me gusta" le aparezca un Pop Up que diga "¡Gracias por ser parte de esta tradición! Ya podés bajar el descuento a tu dispositivo. Y un botón para descargarse un PDF fake que solo diga Paty.

Podrás tenerlo para mañana al mediodía o a la tarde?

El manual de marca de Paty te lo manod por mail por las dudas.

abrazo

**Comment by LeandroBraier** [comment]
Va el manual de marca por acá:

https://www.dropbox.com/s/q83gg84oeajoqnh/Resumen%20Manual%20de%20Marca%20Paty.zip?dl=0

Fijate que cambié la tipografía a Meta Plus. Esa es la correcta.

**Comment by braulio-evangelisti** [comment]
Esta dentro del marco de algo mas grande o una tematica en particular? Es exclusiva para chile o tradicion en general? pregunto para no poner algun elemento descolocado.

2) Hay alguna foto de producto del pack grande de Paty?

Para mañana a la tarde esta.

Abrazo

**Comment by LeandroBraier** [comment]
Es solo para Chile. Está en el marco de una propuesta creativa que estamos haciendo para Paty Chile. Esta landing se vería mediante tecnología NFC en un plato de una hamburguesa. Cuando la persona apoya el movil en el plato se le activaría esta URL. Es para impresionar al ejecutivo que espera nuestra propuesta.

Te paso en un toque la foto del Pack, no problem.

abrazo y gracias!

**Comment by braulio-evangelisti** [comment]
Buenisimo. Ahi me llego todo por mail Lea. Mañana temprano sigo. Abrazo.

**Comment by braulio-evangelisti** [comment]
Fijate de actualizar la url ahora lea

http://www.benteveo.tv/_patylanding/

Abrazo

**Comment by LeandroBraier** [comment]
Quedó muy lindo Brau! Gracias!

Te aviso si hay algun cambio más mañana o pasado.

Abrazo

**Comment by LeandroBraier** [comment]
Brau, está muy bueno. Ahora lo que tenemos que hacer es cambiarlo a la estética que va a tener nuestra presentación al cliente, que es distinta. 

Tomá como base el PSD llamado slide 7 que está subido acá:

https://www.wetransfer.com/downloads/6f40a36d37a531bea83e910a13ad127e20150730152109/f519c5

Además de eso, necesito que ya lo armes responsive porque esta landing viene de un código QR por lo cual se va a ver directamente en mobile. Puede ser para mañana todo bien pero manteniendo la misma URL.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea tenes las fuentes? Voy a tener que pasar todos los textos a imagen porque no las encontre como fuentes web.

**Comment by LeandroBraier** [comment]
Ya te las paso Brau.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Como venis Brau con esto?

**Comment by braulio-evangelisti** [comment]
Ahi resubi unos fix de css, cuando tengas un segundo si podes probra de entrar de nuevo desde el celu a ver si seguis viendo los bordes del contenedor con esa pequeña separacion.

Abrazo

**Comment by LeandroBraier** [comment]
Ahora si, quedó perfecto Brau!

Gracias!
