### ISSUE TITLE
Mock Up Color Room o Proxim

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#3]
Fede, estamos trabajando los templates y es realmente difícil porque depende mucho de la mano que tengamos con el diseño (y yo no tengo mucha). Eze y yo estamos armando versiones. Te pido que nos sumes al menos una versión de alguno de estos dos templates para la tarde. Llegarás con alguno?

Te paso una base del que estoy armando yo a duras penas para que veas los textos que uso y demás. Tenés todo el pack completo que le mandé a Eze en http://we.tl/sVW5dgw8H1

El manual de marca está en http://we.tl/JcQKQ43sOk

Confirmame si recibiste todo porfa

abrazo
![color room en boca de todos](https://cloud.githubusercontent.com/assets/6719872/2957320/9e8df9fe-da9d-11e3-871a-07319c4fde60.jpg)

**Comment by LeandroBraier** [comment]
De hecho el degradé de color no va, en el manual de marca no está permitido, lo usé porque estaba probando cosas.

**Comment by FAAREIA** [comment]
Oka, no hay drama. Empiezo ya mismo. Puedo elegir cualquier template?

2014-05-13 9:57 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Color Room o Proxim preferentemente. Gracias!

On Tue, May 13, 2014 at 12:10 PM, Federico Arena
notifications@github.comwrote:

> Oka, no hay drama. Empiezo ya mismo. Puedo elegir cualquier template?
> 
> 2014-05-13 9:57 GMT-03:00 LeandroBraier notifications@github.com:
> 
> > De hecho el degradé de color no va, en el manual de marca no está
> > permitido, lo usé porque estaba probando cosas.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/LeandroBraier/PatyWeb/issues/3#issuecomment-42950833>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/3#issuecomment-42967822
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
oka

2014-05-13 12:16 GMT-03:00 LeandroBraier notifications@github.com:

> Color Room o Proxim preferentemente. Gracias!
> 
> On Tue, May 13, 2014 at 12:10 PM, Federico Arena

**Comment by FAAREIA** [comment]
voy por color room

2014-05-13 12:22 GMT-03:00 Federico Arena arena.federico@gmail.com:

> oka
> 
> 2014-05-13 12:16 GMT-03:00 LeandroBraier notifications@github.com:
> 
> Color Room o Proxim preferentemente. Gracias!
> 
> > On Tue, May 13, 2014 at 12:10 PM, Federico Arena
