### ISSUE TITLE
Template para Sitio de Patyviena

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#4]
Necesito que busques un template muy simple para un sitio muy básico y simple de Patyviena donde solo subiendo una gráfica ya quede hecho.

Patyviena es una subpágina de Paty pero como es otro público queremos que esté en sitio aparte y que solo por 1 link quede relacionado con Paty Viena

**Comment by FAAREIA** [comment]
Ok lea. Decime que secciones/contenidos va a tener asi busco bien bien.

Abrazo

**Comment by LeandroBraier** [comment]
Practicamente nada tendría. Un formulario de contacto y un link de info
general. Es una web bien bien simple y visual para que redireccionemos
desde la web principal de Paty. Casi una landing como la de Amamos Cocinar
con vos.

2014-05-15 17:01 GMT-03:00 Federico Arena notifications@github.com:

> Ok lea. Decime que secciones/contenidos va a tener asi busco bien bien.
> 
> Abrazo
> 
> El 15 de mayo de 2014, 12:55, LeandroBraiernotifications@github.comescribió:
> 
> > Necesito que busques un template muy simple para un sitio muy básico y
> > simple de Patyviena donde solo subiendo una gráfica ya quede hecho.
> > 
> > Patyviena es una subpágina de Paty pero como es otro público queremos
> > que
> > esté en sitio aparte y que solo por 1 link quede relacionado con Paty
> > Viena
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/LeandroBraier/PatyWeb/issues/4>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/4#issuecomment-43257690
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
ok, busco landing page entonces. ALgo asi con un form.

Abrazo

**Comment by FAAREIA** [comment]
Son todos más o menos iguales. Fijate si sirve para el tipo de contenido que van a meter y para el formulario, que de última se le agregarán campos.

http://themeforest.net/item/crossway-startup-landing-page-template/full_screen_preview/7342227
http://themes.worksofwisnu.com/?theme=PaidjooLanding
http://themeforest.net/item/advisa-marketing-landing-page/full_screen_preview/7321265
http://themeforest.net/item/supernote-one-page-landing-page/full_screen_preview/6756905
http://themeforest.net/item/approach-html-landing-page/full_screen_preview/7401489
http://unbouncepages.com/all-in-one-base/

Avisame y sino busco más
abrazo

**Comment by LeandroBraier** [comment]
Me gustan estas dos:

http://themeforest.net/item/crossway-startup-landing-page-template/full_screen_preview/7342227

http://themeforest.net/item/approach-html-landing-page/full_screen_preview/7401489

De todas formas buscate un par más pero en las cuales lo importante sea la
imagen de fondo sola, que el formulario de contacto sea solo un item en el
menu que se despliega pero que no esté de entrada. No hace falta que sea
Parallax o All in One. Solo necesitamos una One Page digamos.

abrazo

On Fri, May 16, 2014 at 11:35 AM, Federico Arena
notifications@github.comwrote:

> Son todos más o menos iguales. Fijate si sirve para el tipo de contenido
> que van a meter y para el formulario, que de última se le agregarán campos.
> 
> http://themeforest.net/item/crossway-startup-landing-page-template/full_screen_preview/7342227
> http://themes.worksofwisnu.com/?theme=PaidjooLanding
> 
> http://themeforest.net/item/advisa-marketing-landing-page/full_screen_preview/7321265
> 
> http://themeforest.net/item/supernote-one-page-landing-page/full_screen_preview/6756905
> 
> http://themeforest.net/item/approach-html-landing-page/full_screen_preview/7401489
> http://unbouncepages.com/all-in-one-base/
> 
> Avisame y sino busco más
> abrazo
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/4#issuecomment-43338328
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Fijate estos dos:

http://demo.drythemes.com/index.php?theme=theBigBang
http://themeforest.net/item/flat-responsive-coming-soon-landing-page/full_screen_preview/6298500(en
este podemos hacer que el form aparezca desde un botón que hagamos)
http://themeforest.net/item/wda-creative-responsive-landing-page/full_screen_preview/6057930(idem
anterior)

Avisa si te parecen OK
abrazo

**Comment by LeandroBraier** [comment]
Me parecen perfectos estos 3. Los veo con Eze, gracias!

**Comment by LeandroBraier** [comment]
Lo vemos en la reunión de mañana. Nos gusta algo más como esto:

http://themeforest.net/item/agriculture-allinone-woocommerce-wp-theme/5819692?WT.ac=search_item&WT.seg_1=search_item&WT.z_author=cmsmasters

**Comment by marcsuse** [comment]
ojo que es Wordpress

**Comment by LeandroBraier** [comment]
Si, gracias MS. En realidad no lo compramos, lo tomamos de referencia pero
a Fede le lleva menos tiempo y laburo armarlo él con la refe.

abrazo

On Thu, May 22, 2014 at 11:16 AM, marcsuse notifications@github.com wrote:

> ojo que es Wordpress
> On May 20, 2014, at 6:07 PM, LeandroBraier notifications@github.com
> wrote:
> 
> > Lo vemos en la reunión de mañana. Nos gusta algo más como esto:
> > 
> > http://themeforest.net/item/agriculture-allinone-woocommerce-wp-theme/5819692?WT.ac=search_item&WT.seg_1=search_item&WT.z_author=cmsmasters
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/PatyWeb/issues/4#issuecomment-43893675
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Quedó este y ya tenemos el diseño aprobado. Podés empezar a maquetarlo mientras resolvemos tema animación. Sigue siendo prioridad Sitio Paty principal.

Te subí el diseño en PATY MAQUETADOR/ PATYVIENA

La única imagen que está aprobada para el slider es la que está en el PNG que te paso junto con el PSD.

abrazo

**Comment by FAAREIA** [comment]
Lea, el sitio era de una sola página no? Digo porque veo que pusieron 4 secciones arriba.

**Comment by LeandroBraier** [comment]
Si, es una sola.

**Comment by FAAREIA** [comment]
ok, entonces maqueto el PSD y el encabezado lo adapto para que vaya solo el logo sin las secciones

**Comment by LeandroBraier** [comment]
Dale, me parece bien. De todas formas estemos abiertos a que más adelante
se puedan sumar las secciones y se pueda enriquecer en el sitio. Es una
cuenta que queremos hacer crecer.

2014-06-10 13:17 GMT-03:00 Federico Arena notifications@github.com:

> ok, entonces maqueto el PSD y el encabezado lo adapto para que vaya solo
> el logo sin las secciones
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/4#issuecomment-45636039.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Esto lo tenés para el lunes?

**Comment by FAAREIA** [comment]
Hola Lea, estuve con unos lios y no pude avanzar con nada. Hoy voy a tratar de avanzar, si lo necesitan el lunes está para el lunes, pero si se puede mejor el martes.

**Comment by LeandroBraier** [comment]
Hola, Fede. A esta maquetación necesito que le agregues dos cosas:
1. Algún diseño que complete más el header, para que no quede tan vacío.
2. Ponerle al pie el "Desarrollado por Benteveo" con logo y link al sitio web en el logo.

abrazo

**Comment by LeandroBraier** [comment]
Cierro este y abro otro con modificaciones igual que Paty.
