### ISSUE TITLE
Delegación Sitio Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#5]
Marce, teniendo en cuenta que queremos tener el sitio web para principios de Junio deberíamos ir tramitando esto. Qué necesitás que le pidamos a Maria? Quedó pendiente de su lado pasarnos los datos del contacto que tiene el dominio, pero podemos ir avanzando en algo?

**Comment by mkreyness** [comment]
Nada en particular, cuando se pueda habra que apuntar los DNS al IP de 
Duplika y gestionar con soporte de Duplika que respondan adecuadamente.
Internament necesito saber cual es el dominio, y en que carpeta va a 
estar el sitio (esto es tema de Fede), asi agrego el redireccionamiento 
dentro del servidor (como esta el de "amamos").

No tengo muy claro como es el tema de tener multiples dominios con el 
plan en Duplika, si estamos haciendo todo como se debe o en realidad 
estamos haciendo una gran truchada.

**Comment by FAAREIA** [comment]
Es asi, tenes 1 dominio y los otros como parked domain o dominio apuntado.
El de amamos esta apuntado.

**Comment by marcsuse** [comment]
Yo contrataria otro hosting separado

**Comment by LeandroBraier** [comment]
Marcelo, ya tengo el contacto del webmaster de Paty para pedirle los DNS.

Matias.Parente@groupm.com

¿Me decís bien qué le pido así vamos ganando tiempo?

**Comment by mkreyness** [comment]
Me preguntas a mi o a MS ?
Lo que en algun momento van a tener que hacer segun entiendo es apuntar 
el dominio al servidor, pero yo no tengo nada claro porque nunca vi la 
respuesta de si se contrató un hosting para Paty.

**Comment by LeandroBraier** [comment]
Te preguntaba a vos por MS está de viaje.

Por ahora no tenemos un hosting para Paty. Creo que eso también lo ve MS.

Lo que yo te preguntaba es qué necesitamos para apuntar el dominio al
servidor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-08 16:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Primero hay que definir justamente cual es ese servidor.
Suponiendo que por ahora lo quieran apuntar al mismo hosting de 
benteveo.tv, hay dos posibilidades:

1) declarar el dominio (paty.com.ar ?) en el mismo DNS del servidor de 
benteveo (nameserver-1/2.internetya.com) y pasarle esos nuevos DNS a 
Matias Parente para que lo cambie en nic.ar (si es que Matias Patente 
tiene acceso a modificar en nic.ar)

2) Pasarle a Matias Patente los IP de benteveo.tv y que ajuste los 
registros de los DNS actuales (nixe.com/nixe.biz) a que apunten al IP de 
benteveo.tv.

**Comment by LeandroBraier** [comment]
MK, me pasaron el acceso al FTP de paty.com.ar. Con esto podés ya delegar ese dominio al sitio en el hosting actual?

FTP: 69.73.150.22 http://69.73.150.22/~patycom/
usuario: paty@paty.com.ar
pass: Sa)N&rX&$;KX

Yo igual les estoy pidiendo que nos permitan tener el dominio nosotros, se están haciendo los boludos entiendo. Sino, son boludos. Pero porfa confirmame qué podemos hacer con esta info.

abrazo

**Comment by FAAREIA** [comment]
Para delegar hay que tener acceso a nic.ar y los datos de los dns que son siempre los mismos en Duplika

**Comment by mkreyness** [comment]
Seria un milagro, ya que el FTP se usa para administrar contenidos, nada 
que ver con dominios.
La delegacion se hace cambiando los DNS en nic.ar, para lo cual lo que 
hay que tener son los datos para acceder en nic.ar. Actualmente tiene 
dnss de NIXE.COM, el hosting actual.
Lo correcto sería que cambien eso a ns1/ns2.duplika.com y recien ahi lo 
podremos manejar nosotros, porque se administraria desde el hosting nuevo.

**Comment by LeandroBraier** [comment]
Si, entiendo eso. El tema es que BRF quiere sacarse de encima a esta gente y por eso no quiere que el dominio siga a nombre de ellos. Por eso les pide el acceso a Nic.ar directamente y no solo la delegación. Los mantengo informados. Gracias!

**Comment by LeandroBraier** [comment]
MK, URGENTE:

Ya nos hicieron la delegación de los dominios de Paty y Patyviena y da error el sitio.

URGENTE TENEMOS QUE HACER QUE SE VEA EL SITIO NUEVO.

http://paty.com.ar/

http://patyviena.com.ar

**Comment by mkreyness** [comment]
Necesito saber entonces cual es la pagina a la que tengo que 
redireccionar, no tengo idea cual es.
Fede ?

**Comment by FAAREIA** [comment]
Vos tenes los datos de acceso MK?
Necesito entrar al CPanel

**Comment by mkreyness** [comment]
Pero es el de danica ?

danicase
7876mdrxYD

**Comment by FAAREIA** [comment]
Olvidate, el acceso es:
patycoma
d89Uje1zV5

A Paty lo meto en el root.
A PAtyviena lo mejor en la subcarpeta patyviena?
Habría que ahcer algun redirect? o esa magia tuya?

**Comment by mkreyness** [comment]
Es otro hosting entonces ? Si nunca me cuentan nada....
Para hacer mi magia, primero tengo que poder entrar por SSH y ver si 
esta instalado lo necesario.

**Comment by LeandroBraier** [comment]
Es el hosting igual que el que contratamos para Paty. Vos me dijiste que
usemos el mismo y vos después hacías esta magia. El acceso para vos es el
que te pasó Fede:

patycomad89Uje1zV5

Necesito resolverlo urgente porfa

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
jajajajaja, todo urgente! O_O

**Comment by LeandroBraier** [comment]
jajaj Disculpen, es que pensé que ya lo teníamos resuelto! Hace 1 mes le
estoy pidiendo al cliente que haga la delegación, tuvimos que hablar con
una agencia anterior, todo un quilombo, y una vez que hacen la delegación,
resulta que nosotros no subimos nada al hosting!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:35 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Pero "el mismo" no significa "otro que sea igualito", significa 
"REALMENTE el mismo".
Es como que me digas que el depto de debajo de mi casa es "el mismo" que 
el mio, te aseguro que mi llave no lo abre.

Eso que paso Fede es el cpanel, desde ahi no puedo hacer nada, necesito 
acceso SSH, hay que pedirselo a la gente de Duplika.

**Comment by LeandroBraier** [comment]
MK, ES EL MISMO HOSTING. Vos me dijiste que usabamos el mismo hosting con
los mismos DNS. No entiendo cual es la confusión.

Ahora te reenvio el mail completo de Duplika. Quizás ahí ya está el acceso
SSH.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:39 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Te llegó? Hay un acceso a FTP aparte del que te di. Es este:
- FTP host: ftp.paty.com.ar
- FTP (acceso temporal): 67.225.221.23

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:42 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
No me sirve. No puedo instalar programas desde FTP. Necesito SSH.

**Comment by FAAREIA** [comment]
Me acuerdo que con Duplika algo habías hablado y creo que hasta te
habilitaron algo en el server. Sin embargo en el Cpanel hay algo para
generar las claves ssh, o algo ssh

**Comment by LeandroBraier** [comment]
Te fijás MK?

Confirmame sino te lo tramito con Duplika. Mientras tanto queda el link a
/patyviena/

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:48 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
ATENCIÓN

momentaneamente esta url: patyviena.com.ar
lleva a esta url: http://paty.com.ar/patyviena/

Es un fix rápido, y no es original de MK en el que la URL quedaría POSTA

**Comment by mkreyness** [comment]
Si tienen IP distintos, son distintos servers, distintas maquinas, 
distinta configuracion, distinto todo, hay que instalar todo de cero.
(Yo decia "mismo" como danica y amamoscocinar estan en el mismo server). 
Pense que las 4 cosas iban a estar ahi.

NO hay ningun problema en que Fede instale todo lo de paty.com.ar ahi, 
eso no requiere nada de mi.
Para lo unico que me necesitan es para hacer lo de patyviena.com.ar, que 
esta "en el mismo server" que paty.com.ar.
Solo que yo nunca supe de la existencia de este server separado.

**Comment by FAAREIA** [comment]
Recien ahora lo dieron de alta.
Es como decis vos, solo hay que hacer esa redirección que también "spoofea"
la url.

**Comment by mkreyness** [comment]
En su momento lo habilitaron pero para el server "danicase", el que yo 
creia que iba a albergar estos dos sitios.
Para duplika Paty es entonces un cliente totalmente separado, lo que 
hayan hecho para Danica no aplica automaticamente a Paty.
Ya hice todo lo de las claves, pero eso no hace que lo habiliten en el 
server.
Me va a servir, cuando lo habiliten.
El cliente del server "patycoma" tiene que pedirle a Duplika que 
habilite el puerto SSH en este server.

**Comment by mkreyness** [comment]
Pero si los datos de acceso son de un mail del 10 de julio...

**Comment by LeandroBraier** [comment]
Lo podemos hacer, Marce, no hay problema.

Qué le pido entonces. Decime EXACTAMENTE qué le pido así no perdemos más
tiempo.

¿Que habilite el server SSH para el cliente "patycoma"?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 18:00 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Que habiliten el acceso SSH al server "paty.com.ar", cuyo usuario es 
"patycoma".

**Comment by LeandroBraier** [comment]
Ok, ya lo pido!!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 18:11 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Paso aca la pregunta de Fede:Otra cosa,
```

Marce, ya saqué el dominio apunto del Panel de Control y cuando voy a "
patyviena.com.ar" me va a "paty.com.ar/patyviena/" como debe de ser,
PEEEEEEEEEEEEERO, la url no queda como "patyviena.com.ar", sino que queda "
paty.com.ar/patyviena/"

No sabia que se podia redireccionar directamente desde el CPANEL.
Podrias probar de poner que:

patyviena.com.ar directorio "/"  redireccione no a paty.com.ar/patyviena , sino a patyviena.com.ar/patyviena

No deberia entrar en loop, porque el primero dice que aplica solo a "/"

```
De todos modos A MI asi como esta, no me esta andando bien, me sale
esto:SORRY!
If you are the owner of this website, please contact your hosting
provider: webmaster@patyviena.com.ar
It is possible you have reached this page because:El 17/09/2014 18:14, LeandroBraier
  escribió:

  Ok, ya lo pido!!!
```

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 18:11 GMT-03:00 mkreyness notifications@github.com:

```
    Que habiliten el acceso SSH al server "paty.com.ar", cuyo usuario es
```

"patycoma".

On 17/09/2014 06:07 p.m., LeandroBraier wrote:

```
      Lo podemos hacer, Marce, no hay problema.
```

Qué le pido entonces. Decime EXACTAMENTE qué le pido así no perdemos más
tiempo.

¿Que habilite el server SSH para el cliente "patycoma"?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 18:00 GMT-03:00 mkreyness notifications@github.com:

```
        Pero si los datos de acceso son de un mail del 10 de julio...
```

On 17/09/2014 05:56 p.m., Federico Arena wrote:

```
          Recien ahora lo dieron de alta.
```

Es como decis vos, solo hay que hacer esa redirección que también
"spoofea"
la url.

El 17 de septiembre de 2014, 17:54,

```
      mkreyness<notifications@github.com>



          escribió:



            Si tienen IP distintos, son distintos servers, distintas maquinas,
```

distinta configuracion, distinto todo, hay que instalar todo de

```
      cero.




            (Yo decia "mismo" como danica y amamoscocinar estan en el mismo


          server).


            Pense que las 4 cosas iban a estar ahi.
```

NO hay ningun problema en que Fede instale todo lo de

```
      paty.com.ar ahi,




            eso no requiere nada de mi.
```

Para lo unico que me necesitan es para hacer lo de

```
      patyviena.com.ar,



          que


            esta "en el mismo server" que paty.com.ar.
```

Solo que yo nunca supe de la existencia de este server separado.

On 17/09/2014 05:47 p.m., Marcelo Kreyness wrote:

```
              No me sirve. No puedo instalar programas desde FTP. Necesito SSH.
```

On 17/09/2014 05:44 p.m., LeandroBraier wrote:

```
                Te llegó? Hay un acceso a FTP aparte del que te di. Es este:
```
- FTP host: ftp.paty.com.ar
- FTP (acceso temporal): 67.225.221.23

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:42 GMT-03:00 Leandro Braier

```
      <leandrobraier@gmail.com



          :







                  MK, ES EL MISMO HOSTING. Vos me dijiste que usabamos el mismo


                hosting con


                  los mismos DNS. No entiendo cual es la confusión.
```

Ahora te reenvio el mail completo de Duplika. Quizás ahí ya

```
          está el




                acceso


                  SSH.
```

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:39 GMT-03:00 mkreyness

```
      <notifications@github.com>:
```

Pero "el mismo" no significa "otro que sea igualito",

```
      significa








                    "REALMENTE el mismo".
```

Es como que me digas que el depto de debajo de mi casa es "el

```
                mismo" que



                    el mio, te aseguro que mi llave no lo abre.
```

Eso que paso Fede es el cpanel, desde ahi no puedo hacer

```
      nada,






                necesito



                    acceso SSH, hay que pedirselo a la gente de Duplika.
```

On 17/09/2014 05:34 p.m., LeandroBraier wrote:

```
                      Es el hosting igual que el que contratamos para Paty.









      Vos me






                dijiste que




                      usemos el mismo y vos después hacías esta magia. El









      acceso para






                vos es



                    el


                      que te pasó Fede:
```

patycomad89Uje1zV5

Necesito resolverlo urgente porfa

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 17:31 GMT-03:00 mkreyness

```
          <notifications@github.com>:










                        Es otro hosting entonces ? Si nunca me cuentan nada....
```

Para hacer mi magia, primero tengo que poder entrar

```
      por SSH y






                ver si





                        esta instalado lo necesario.
```

On 17/09/2014 05:24 p.m., Federico Arena wrote:

```
                          Olvidate, el acceso es:
```

patycoma
d89Uje1zV5

A Paty lo meto en el root.
A PAtyviena lo mejor en la subcarpeta patyviena?
Habría que ahcer algun redirect? o esa magia tuya?

El 17 de septiembre de 2014, 17:09, Federico
Arenaarena.federico@gmail.com
escribió:

```
                            Vos tenes los datos de acceso MK?
```

Necesito entrar al CPanel

El 17 de septiembre de 2014, 17:04,

```
                      mkreyness<notifications@github.com






                            escribió:
```

Necesito saber entonces cual es la pagina a la que

```
          tengo que











                              redireccionar, no tengo idea cual es.
```

Fede ?

On 17/09/2014 04:50 p.m., LeandroBraier wrote:

MK, URGENTE:

Ya nos hicieron la delegación de los dominios de

```
          Paty y







                      Patyviena



                          y da




                                error el sitio.
```

URGENTE TENEMOS QUE HACER QUE SE VEA EL SITIO

```
      NUEVO.
```

http://paty.com.ar/

http://patyviena.com.ar

—
Reply to this email directly or view it on GitHub
<

```
      https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55949777











                          .
```

—
Reply to this email directly or view it on GitHub

```
                      <















      https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55951436















                              .
```

—
Reply to this email directly or view it on GitHub

```
                      <















      https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55954224











                          .
```

—
Reply to this email directly or view it on GitHub

```
                      <















      https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55955190





              .
```

—
Reply to this email directly or view it on GitHub
<

```
      https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55955609





              .
```

—
Reply to this email directly or view it on GitHub

```
                <











    https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55956328>









                    .
```

—
Reply to this email directly or view it on GitHub
<

```
      https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55957036



          .
```

—
Reply to this email directly or view it on GitHub

```
      <https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55958613



          .
```

—
Reply to this email directly or view it on GitHub

```
      <https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55958943



          .
```

—
Reply to this email directly or view it on GitHub

```
      <https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55959541
```

.

—
Reply to this email directly or view it on GitHub
<https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55960324
.

—
Reply to this email directly or view it on GitHub
https://github.com/LeandroBraier/PatyWeb/issues/5#issuecomment-55960983.

---

**Comment by LeandroBraier** [comment]
A mí también me pasa lo mismo. Ahora me intenta ir a patyviena.com.ar
directamente y termina dando sitio no disponible.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 21:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Volvamos a la versión anterior cuanto antes porfa. La de
paty.com.ar/patyviena/.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-17 22:48 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
Pero entiendo que nadie toco nada, solo empezó a andar mal...
Cuando este el acceso SSH lo arreglo en 2 patadas.

**Comment by LeandroBraier** [comment]
Pero va a quedar toda la noche asi? Cambiemoslo a paty.com.ar/patyviena/
mientras tanto. Está online en el sitio de Paty!

**Comment by mkreyness** [comment]
No tengo idea que habia puesto cuando andaba, solo opiné sobre lo que 
vi, y no cambie nada, el unico que puede saber como estaba antes cuando 
andaba es Fede.

**Comment by FAAREIA** [comment]
Yo entra a patyviena.com.ar y va a paty.com.ar/patyviena/ por ahora esta
bien.
Por otra parte, ya esta lo responsivo de Patyviena.

**Comment by FAAREIA** [comment]
Ahi lo puse nuevamente.
Mañana veamoslo mejor marce en un mailing nuevo sin tanto historial, ya
estoy mareado

**Comment by LeandroBraier** [comment]
Exacto. Mañana les paso el ticket aparte y cierro este. Muchas gracias Fede!
