### ISSUE TITLE
Modificación en Contenidos Sitio Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#7]
Fede, te paso corrección de contenidos enviada por el cliente. Vamos a mantener en este ticket todo lo que es contenidos (incluidos materiales visuales que te adjunto por WeTransfer). 

Estoy cerrando el de maquetación y creo otro ticket con los cambios restantes en diseño.

Sección Productos (cambia el orden y algunos textos internos):

Paty Clásico (ambos packs juntos)
Las de Siempre
Saboreá el clásico insuperable de Paty. 
¡Carne 100% argentina lista para disfrutar como más te guste!

Paty Finitas
Para amarte una doble!
Con dos Paty Finitas podés crear una súper hamburguesa, donde el sabor se multiplica. 

Paty Light
Para los moderados…
Y si te estás cuidando, no te prives del sabor. Paty light, es más light pero igual de rica

Paty Express
Para los apurados…
Sino sufrís de ansiedad, no tenés por qué esperar. Paty Express se cocinan más rápido y vos disfrutás al instante. 

Party Super
Para los que quieren más…
Nunca es mucho para un Paty. Paty súper, máximo sabor y más carne.

Patynesa
Y para variar. 
Y qué tal si comemos un Paty a la milanesa? Patynesa, para vos que amás Paty y te gusta variar. 

Sección Campañas

Quitar la campaña 2002 por el momento.

Sección Novedades

Conocé nuestros nuevos perfiles de redes sociales!

Vos creciste, nosotros cambiamos para acompañarte. 
Ahora no hablás por teléfono, te comunicás de otra forma. FB, Twitter… Estás cerca de lo que te gusta en todo momento. Por eso, era hora de que Paty esté donde vos estás… Buscanos! 

Viví el Mundial con Paty

Este mundial vas a querer comértelos a todos! Paty está con vos, seguí la campaña en redes y participá con tus amigos.  En donde hay un sentimiento argentino, hay un Paty!

Paty presente

Donde estés,  estamos…
Te pasamos la data para que encuentres un verdadero Paty. 
Aquí encontrarás la info para encontrarte con el mejor sabor en los eventos argentinos, más destacados, La Rural, el TC, y muchos más. Enterate dónde encontrarnos.

**Comment by FAAREIA** [comment]
Lea, faltaría la data nutricional e imagen del producto "Patynesa"

**Comment by LeandroBraier** [comment]
Te lo subí todo en dropbox. Lo tneés ahí.

El PDF de info y la imagen en producto en PSD.

On Wed, Jun 25, 2014 at 10:55 AM, Federico Arena notifications@github.com
wrote:

> Lea, faltaría la data nutricional e imagen del producto "Patynesa"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/7#issuecomment-47103514.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, van modificaciones en contenidos:

Sección Productos:
1. ~~"siempre" con minúsculas en Paty Clásico~~
2. ~~Súper con tilde en mayúsculas en Paty Súper~~
3. ~~A todas las descripciones agregar punto final.~~
4. ~~Modificación en descripción PatyNesa: "Y para variar: qué tal si...~~

Sección Campañas:
1. ~~Quitar la palabra "campaña" de los títulos de cada campaña. Que solo diga el año.~~

**Comment by FAAREIA** [comment]
~~Lea, si pongo el año en campañas, se va a repetir con el título, esta ok igual?. Y si esta OK, necesitaría saber el año de la campaña "Paty 50 años queriéndonos"~~
Olvidate, había entendido mal

**Comment by LeandroBraier** [comment]
No, ese queda asi. Lo que no quiere el cliente es leer "Campaña 2000". En
ese caso quedaría solo "Año 2000". Pero en los que tiene titulo mas lindo
dejemoslo asi.

**Comment by LeandroBraier** [comment]
Fede, en Productos hay dos errores.

~~Paty Clásico: falta el punto después de "siempre".~~

~~Patynesa: sobra el primero "Y para variar."~~

abrazo

**Comment by FAAREIA** [comment]
Lea, ahi subi otra actualización. A los años los dejé como dijiste en el post anteúltimo.

**Comment by LeandroBraier** [comment]
Fede, llegó el feedback del cliente. Son cambios simples por suerte:
1. INTRO: en todos los textos en que aparece la palabra Paty (ejemplo: Paty con amigos) tiene que ir Paty en mayúscula.
2. INTRO: donde dice -reunión con amigos- cambiar por -asado en familia-
3. En la sección de productos, Paty Súper está sin tilde en la U. Me refiero en la tabla nutricional.
4. Cambiar el título y el texto del artículo que dice "Viví el Mundial con Paty".

Título nuevo: "Paty es Argentina"

Texto: Como casi todos los argentinos, Paty acompaña a los deportistas y representantes del país en todas las competencias deportivas. Futbol, Rugby, Basketball... Porque Paty es un sentimiento que genera pasiones. Mirá cómo vivimos haciendo de la épica deportiva un momento Paty."

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_paty9/home.html

La palabra "Paty" al lado de la hamburguesa de Comunidad, la tome como parte de la intro y la puse en mayúscula también.

**Comment by LeandroBraier** [comment]
Gracias!

Creo que hubo una pequeña confusión. En realidad con mayúscula me refería a la Primer Letra Mayúscula, no TODO en mayúscula. Por ejemplo, quedaría así:

"Paty con amigos"

"Paty a la parrilla"

El de PATY TE QUIERO puede quedar así porque está TODO en mayúsculas.

Avisame nomás cuando esté esto.

abrazo

**Comment by FAAREIA** [comment]
Ahora si, dale F5 asi actualiza las imágenes

**Comment by LeandroBraier** [comment]
Perfecto Fede! Gracias!

Cierro este ticket por ahora.

abrazo
