### ISSUE TITLE
Modificación en Diseño Paty

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#8]
1. CAMBIO DE IMAGENES:

a. Cambiar el Paty de la sección Comunidad por una versión más cargada, con panceta. Te envío esta imagen por mail.

b. ~~Cambiar la imagen de fondo anterior a la sección Novedades por una donde se vea más la carne y menos el pan. Buscar en DepositPhotos~~

c. ~~Cambiar imagen de fondo anterior a la sección Productos por una de Patys en la parrilla. (Estamos esperando esta imagen de parte del cliente).~~
1. ~~Repetir el recuadro irregular del menú en los títulos de cada producto (ponelos en el fondo de la imagen al menos para que el cliente vea como queda y se de cuenta que no quedan bien).~~
2. ~~ANIMACIÓN: en los casos en que la sección comunidad no entre entera, que quede oculta el título Comunidad, que el titular parezca "Cada 10 minutos alguien…" Consulta: ¿Para cuándo va a estar la primera versión de la animación?~~
3. ~~Creá una paleta en base al manual de marca para el sitio con todos los colores saturados que usaste, así lo respetamos siempre y lo podemos pasar a los diseñadores. Envianosla por mail a la paleta para enviarle al cliente y que la apruebe final.~~
4. ~~¿Existe la posibilidad de agregar un texto breve en mouse over sobre cada video de la sección campañas?~~ 
5. ~~Falta el Desarrollado por Benteveo en Paty. Recordá quitar la linea gris.~~

**Comment by FAAREIA** [comment]
Hola Lea, ahora ando con la animación. Luego de la entrega veo los puntos.
Esperemos que para mañana ya pueda entregarles algo. En IE8, la rotación
funciona, pero cuando se escala el objeto (el zoom out del video), se
rompe.

**Comment by LeandroBraier** [comment]
Ok, pensemos entonces en una versión sin zoom out pero con scale general
para IE8, se podrá?

2014-06-23 17:56 GMT-03:00 Federico Arena notifications@github.com:

> Hola Lea, ahora ando con la animación. Luego de la entrega veo los puntos.
> Esperemos que para mañana ya pueda entregarles algo. En IE8, la rotación
> funciona, pero cuando se escala el objeto (el zoom out del video), se
> rompe.
> 
> El 23 de junio de 2014, 15:28, LeandroBraiernotifications@github.com
> escribió:
> 
> > 1.
> > 
> > Cambiar el Paty de la sección Comunidad por una versión más cargada,
> > con panceta. Te envío esta imagen por mail.
> > 2.
> > 
> > Repetir el recuadro irregular del menú en los títulos de cada producto
> > (ponelos en el fondo de la imagen al menos para que el cliente vea como
> > queda y se de cuenta que no quedan bien).
> > 3.
> > 
> > ANIMACIÓN: en los casos en que la sección comunidad no entre entera,
> > que quede oculta el título Comunidad, que el titular parezca "Cada 10
> > minutos alguien…" Consulta: ¿Para cuándo va a estar la primera versión
> > de
> > la animación?
> > 4.
> > 
> > Creá una paleta en base al manual de marca para el sitio con todos los
> > colores saturados que usaste, así lo respetamos siempre y lo podemos
> > pasar
> > a los diseñadores. Envianosla por mail a la paleta para enviarle al
> > cliente
> > y que la apruebe final.
> > 5.
> > 
> > ¿Existe la posibilidad de agregar un texto breve en mouse over sobre
> > cada video de la sección campañas?
> > 6.
> > 
> > Falta el Desarrollado por Benteveo en Paty. Recordá quitar la linea
> > gris.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/LeandroBraier/PatyWeb/issues/8.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-46900767.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si se puede, el tema es que va a sumar más tiempo a lo que es la
realización de la animación. Serían 2 versiones. Primero avancemos con la
que funciona en lo nuevo, y después nos ocupamos de este navegador próximo
a morir.

**Comment by LeandroBraier** [comment]
Jaja me parece perfecto.

**Comment by LeandroBraier** [comment]
Fede, ya te subí la foto necesaria para el cambio de la 1C. Te estoy debiendo aún la del punto 1A.

**Comment by FAAREIA** [comment]
Lea, esta es la paleta que estuve usando. Todos los colores de texto no sé si los usé, pero esta la escala del más negro al más claro. Los colores que no figuran aca son casos particulares de menor importancia, como los del soporte del título del producto.

$rojo-color: #E42313;
$naranja-color: #FF621E;
$azul-color: #00b5e9;
$amarillo-color: #ffc425;
$verde-color: #008851;
$verde-agua-color: #7bc143;
~~$verde-oscuro-color: #34495E;~~
$rosa-color: #ff3f99;
$violeta-color: #b22dff;

$texto-color-1: #2A2A2A;
$texto-color-2: #4A4A4A;
$texto-color-3: #6A6A6A;
$texto-color-4: #8A8A8A;
$texto-color-5: #AAAAAA;
$texto-color-6: #CACACA;
$texto-color-7: #EAEAEA;

**Comment by FAAREIA** [comment]
Con respecto al hover en campañas, es posible hacerlo y quedaría mucho mejor meterlo dentro de la ventana emergente del video y no cuando te sale "Título + link para ver campaña", ya que ahi no hay mucho espacio en resoluciones menores.

**Comment by LeandroBraier** [comment]
Ok. Hagamoslo en resoluciones mayores y en las menores hagamos como vos decis. Se puede?

**Comment by LeandroBraier** [comment]
Fede. Mañana reunión 16.30 hs en la produ para ver como estamos con el sitio de Paty. Confirmame porfa si podes.

**Comment by FAAREIA** [comment]
Ok la reunion.
Con respecto a la info, pasame los textos que irian y ahi vemos. Todos
depende de la longitud del contenido a agregar.

2014-06-25 18:35 GMT-03:00 LeandroBraier notifications@github.com:

> Fede. Mañana reunión 16.30 hs en la produ para ver como estamos con el
> sitio de Paty. Confirmame porfa si podes.
>

**Comment by LeandroBraier** [comment]
Genial!

De qué info hablamos?

2014-06-25 20:40 GMT-03:00 Federico Arena notifications@github.com:

> Ok la reunion.
> Con respecto a la info, pasame los textos que irian y ahi vemos. Todos
> depende de la longitud del contenido a agregar.
> 
> 2014-06-25 18:35 GMT-03:00 LeandroBraier notifications@github.com:
> 
> > Fede. Mañana reunión 16.30 hs en la produ para ver como estamos con el
> > sitio de Paty. Confirmame porfa si podes.
> > 
> > Federico Arena notifications@github.com escribió:
> > 
> > Conrespectoalhoverencampañas,esposiblehacerloyquedaríamuchomejormeterlodentrodelaventanaemergentedelvideoynocuandotesale"Título+linkparavercampaña",yaqueahinohaymuchoespacioenresolucionesmenores.ReplytothisemaildirectlyorviewitonGitHub.
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47161981.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47172593.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
la de campañas

**Comment by LeandroBraier** [comment]
~~Ahí van los textos para las campañas~~
1. Walkman y “Paty te quiero”. Nacía un clásico
2. La historia se repite. “Paty te quiero cada día más”
3. Paty un sentimiento que se comparte. “Todos queremos Paty”
4. Paty te sigue acompañando. “Paty está siempre”
5. Cuando pedís hamburgues, decís “dame un Paty”. “Paty 50 años
   queriéndonos”
6. Olé, olé, ¡hoy más que nunca!. “Paty un sentimiento”

2014-06-25 20:53 GMT-03:00 Federico Arena notifications@github.com:

> la de campañas
> 
> El 25 de junio de 2014, 20:46, LeandroBraiernotifications@github.com
> escribió:
> 
> > Genial!
> > 
> > De qué info hablamos?
> > 
> > 2014-06-25 20:40 GMT-03:00 Federico Arena notifications@github.com:
> > 
> > > Ok la reunion.
> > > Con respecto a la info, pasame los textos que irian y ahi vemos. Todos
> > > depende de la longitud del contenido a agregar.
> > > 
> > > 2014-06-25 18:35 GMT-03:00 LeandroBraier notifications@github.com:
> > > 
> > > > Fede. Mañana reunión 16.30 hs en la produ para ver como estamos con
> > > > el
> > > > sitio de Paty. Confirmame porfa si podes.
> > > > 
> > > > Federico Arena notifications@github.com escribió:
> > 
> > Conrespectoalhoverencampañas,esposiblehacerloyquedaríamuchomejormeterlodentrodelaventanaemergentedelvideoynocuandotesale"Título+linkparavercampaña",yaqueahinohaymuchoespacioenresolucionesmenores.ReplytothisemaildirectlyorviewitonGitHub.
> > 
> > > > —
> > > > 
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47161981>.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47172593>.
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47172996.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47173438.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, va la lista de lo que hablamos en la reunión de hoy.

Primera etapa: todo esto más reemplazo de fotos en la versión beta actual.

Segunda etapa: agregamos la nueva animación con bajada institucional del punto final de la animación. Lean envia un storyboard con esto antes.

. Modificaciones Diseño:
1. CAMBIO DE IMAGENES

a. Volver al Paty anterior por las dudas

b. Pendiente.

c. Hecho.
1. Cuadro irregular: Letras rojas y el fondo blanco en todos
2. Animación: se corrige sacando el contador
3. Creada.
4. Agregamos dos líneas debajo del embed de YouTube.
5. Que quede alineado a la izquierda.

Agregamos:
1. Que no haya líneas tan sutiles en los fondos, subirle el color. Que sea con trazo más gordo.
2. Agregar fondo en Comunidad, en Novedades y en Contacto
3. Continuar con más polaroids hasta el footer para continuar la idea de instantáneas Paty

En la Animación:
1. Falta la bajada institucional tipo "Todos tenemos un momento Paty…", que explique

Va a entrar con una animación propia en la frase, con menos fotos en cada fase y más "chirimbolos" o "símbolos" que es la que hablamos en la reunión. Es un recorrido más larga hacia abajo con menor cantidad de fotos en cada etapa.

**Comment by LeandroBraier** [comment]
~~Fede, te paso varias fotos posibles para reemplazar la foto de fondo que dijimos hoy y que se vea más carne. Es para el punto 1.b de CAMBIAR IMAGEN~~

http://sp.depositphotos.com/7592171/stock-photo-young-boy-eating-cheeseburger.html?sst=120&sqc=162&sqm=7599&sq=3igamb

http://sp.depositphotos.com/10422359/stock-photo-cute-child-with-burger.html?sst=120&sqc=178&sqm=7599&sq=3igamb

http://sp.depositphotos.com/9753048/stock-photo-man-eating-hamburger.html?sst=660&sqc=681&sqm=7599&sq=3igamb

Descargate la que te sirva más sin problemas.

abrazo

**Comment by LeandroBraier** [comment]
~~Fede, se suma un tema más. Más allá de la paleta que usaste, el cliente pidió específicamente un fondo diferente para cada uno de los productos. Es así:~~

Paty Clásico: Fondo Rojo Paty

Paty Light: Fondo Verde igual que del pack

Paty Super: Fondo Bordó oscuro dentro de la paleta saturada que usamos

Paty Nesa: Fondo Naranja igual que el del pack

Paty Finitas: Fondo amarillo dentro de la paleta

 Paty Espress: Fondo turquesa que ahora tiene Patynesa, siempre dentro de la paleta.

abrazo

**Comment by FAAREIA** [comment]
Lea, estaba poniendo los textos de las campañas y me di cuenta que falta el texto para "Paty te quiero 2002" y sospechosamente esta el texto de la campaña "2000" que fue la que sacamos, puede ser?

**Comment by LeandroBraier** [comment]
Exacto, la sacamos mal entonces. La del 2000 si va y la de 2002 es la que
teníamos que sacar. Debe haber habido algún error de comunicación. Te llegó
también lo de los colores de fondo de los productos?

2014-06-27 9:51 GMT-03:00 Federico Arena notifications@github.com:

> Lea, estaba poniendo los textos de las campañas y me di cuenta que falta
> el texto para "Paty te quiero 2002" y sospechosamente esta el texto de la
> campaña "2000" que fue la que sacamos, puede ser?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/PatyWeb/issues/8#issuecomment-47339683.

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si, me llegó todo, estoy con eso

**Comment by LeandroBraier** [comment]
Por ahora, una sola modificación nueva:
1. ~~La foto de la chica de Ojos celeste  que está arriba de CAMPAÑAS quedó desplazada hacia arriba y no se ve que tiene una hamburguesa en la boca. Desplazarla para que se vea y se entienda eso.~~

**Comment by LeandroBraier** [comment]
Una modificación pequeña en el fondo. La foto de futbolistas que está a la derecha de "Productos" pasala a la izquierda, para que no se superponga con el logo de Paty en algunas resoluciones.

abrazo

**Comment by LeandroBraier** [comment]
Vamos avanzando con la versión responsiva, Fede. Para cuándo estimás que estaría?

**Comment by FAAREIA** [comment]
Hoy lo empiezo y te digo, hubo mucho cambio y no sé en que estado quedó lo que se había hecho.

**Comment by FAAREIA** [comment]
Hola Lea, ahi esta listo lo responsivo de Paty.
También ajuste la intro para IE8 o dispositivos móviles inferiores a 768px de ancho.
En ie8 no hay animación, las fotos fueron reemplazas por un fondo porque ni eso se podia.
En los dispositivos inferiores a 768px de ancho, reordené las fotos en base  a 480px y 320px de ancho.

Por ahora me falta solucionar 2 bugs en IE8, y ya esta listo el preloader pero parece que no funciona. Lo consulto con marce.
También me falta veo eso que decia Marce S., aunque supongo que puede ser la maquina en si y no el navegador.

**Comment by LeandroBraier** [comment]
Gracias Fede! Avisame cuando esté final.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-23 14:51 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hola Lea, ya estan listos los bugs que te decia en IE8. Algunos fueron solucionados, y otros anulados por bugs irregulares, como por ejemplo que se pinte el texto del menú de la sección en que estas.
Por otra parte, necesito el email al que va ir el formulario de contacto.
Fijate que el preloader ya funciona, aunque en IE8 no pero ya le mandé mail a Marce K.

Hablamos!

**Comment by LeandroBraier** [comment]
Gracias Fede! Ahora chequeo.

El mail de contacto es el mismo que el de Danica.

**Comment by FAAREIA** [comment]
Joya Lea, guarda que ahora estamos con marce con el tema del loading. Te aviso cuando este listo.

**Comment by FAAREIA** [comment]
Ya esta listo el preloader para IE8 y los demás navegadores.
ME falta chequear lo que decia Marce S.

**Comment by LeandroBraier** [comment]
Últimos ajustes, Fede:
1. Subir un poco la foto de la parrilla en parallax, para que se vea más tiempo la hamburguesa Paty.
2. De Paty Clásico quitar el pack, que quede solo la caja.

Para el lunes está bien.

abrazo

**Comment by FAAREIA** [comment]
Lo hice ahora, mientras espero lo del video:
www.benteveo.tv/_paty10/

**Comment by FAAREIA** [comment]
Lea, faltaría que me digas cual es el email que va a receibir el formulario de contacto. Recuerdo que una vez me dijiste el mismo que dánica, pero no se cual es y en buscarlo llegar a tardar bastante. Si lo tenes a mano, buenisimo

**Comment by LeandroBraier** [comment]
Está perfecto. Me quedo con el ticket.

EL nuevo video va a estar recién el lunes. Ya tenés todas las landings de
las 18 marcas para ir viendo?

Así ya te doy el OK y solo te queda hacer la versión mobile iOS con nuevo
video.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
consultas@brf-latam.com

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-22 11:55 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahora en un rato te lo envío, ya tenía algunas hechas pero tengo que
cambiar parte del código.
Hablando de Paty, ya agregué el email.

**Comment by LeandroBraier** [comment]
Perfecto, me quedo con el ticket entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-08-22 12:07 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Ya volvió. En la sección de Productos Hay que sacar Paty Clásico x2 y agregar Paty Express x2 con la foto del Pack que te subí al Dropbox Paty Maquetador/ Productos.

abrazo

**Comment by LeandroBraier** [comment]
A esto me refería de Paty Express:

"En la sección de Productos Hay que sacar Paty Clásico x2 y agregar Paty Express x2 con la foto del Pack que te subí al Dropbox Paty Maquetador/ Productos."

Lo primero ya lo hiciste, lo segundo no.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo Lea:
http://www.benteveo.tv/_paty10/home.html
Avisame si esta OK

**Comment by LeandroBraier** [comment]
Fede, está casi OK. Nos pidió el cliente reemplazar la foto de la chica con el pan de hamburguesa que le tapa la boca. Reemplazala por una de estas 3, la que quede mejor:

http://sp.depositphotos.com/2476150/stock-photo-woman-eating-burger.html?sst=0&sqc=59&sqm=625&sq=3ulll7

http://sp.depositphotos.com/49743063/stock-photo-girl-eating-hamburger.html?sst=0&sqc=45&sqm=625&sq=3ulll7

http://sp.depositphotos.com/3733962/stock-photo-woman-eating-burger.html?sq=3ulll7&sst=0

abrazo

**Comment by FAAREIA** [comment]
Esta http://www.benteveo.tv/_paty10/imagenes/animacion/foto-02.jpg
o esta http://www.benteveo.tv/_paty10/imagenes/animacion/fondo.jpg que esta a la izquierda al medio

????

**Comment by LeandroBraier** [comment]
Ninguna de las dos. Es la de la morocha de ojos claros que está entre
Productos y Campañas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-03 11:25 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya esta listo Lea:
www.benteveo.tv/_paty11/

**Comment by LeandroBraier** [comment]
Fijate si la podés achicar a la foto para que se vea más la chica y no
tanto los detalles de su piel.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi lo achiqué un poco, fijate y decime.
F5

**Comment by LeandroBraier** [comment]
Probalo un poco más chico, yo sigo viendo mucho detalle y nada de la cara
de la chica. Termina siendo muy similar a la que está entre novedades y
contacto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Entiendo, fijate ahora

**Comment by LeandroBraier** [comment]
ahora si, perfecto!

Gracias.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
