### ISSUE TITLE
Contenidos Patyviena

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/PatyWeb#9]
Fede, va la devolución del cliente via WeTransfer.

Portfolio y aclaraciones del cliente sobre el contenido del sitio en:

https://www.wetransfer.com/downloads/ed403dea8b1bb0dd41bee79245354af420140621152417/951151bdc3e4bf39189d554e3a63d61320140621152417/e6fc15

Archivos en alta:

https://www.wetransfer.com/downloads/87c8a42db4a79234e7f690fdf3bda9e320140621135538/efbc0e2b74913c13acee5e671310e06720140621135538/f6f896

En síntesis:
1. Subir los productos definitivos que figuran en el portfolio.
2. Quitar los sliders del slideshow y los titulares de colores debajo. Solo dejar la primer foto linda que tenemos y un slideshow no automático que muestre los 5 productos que tenemos en alta.
3. Sumarle el Desarrollado por Benteveo y un Favicon de Patyviena.
4. Texto de formulario de consulta:

"¿Consultas sobre nuestros productos?

Dejanos tus comentarios y sugerencias. Nuestro equipo de especialistas podrá tomarlas en cuenta y responderte."

Ese formulario se envia a consultas@brf-latam.com.

Por ahora cuando tengas estos cambios queda así.

abrazo

**Comment by LeandroBraier** [comment]
Fede, activamos este tema. Lo necesito tener resuelto para el jueves. Llegás?

**Comment by FAAREIA** [comment]
Yo creo que si llegamos, no vi los adjuntos pero recuerdo que el contenido
del sitio era bastante poco. Hoy ya me pongo

**Comment by FAAREIA** [comment]
Lea, me dice que los adjuntos no estan disponibles. Avisa cuando los
vuelvan a subir.

abrazo

**Comment by LeandroBraier** [comment]
Pense que ya los habias bajado. Te los mando a la noche.

Avanza con lo de Benteveo porfa.

Abrazo

**Comment by FAAREIA** [comment]
OK, cuando antes puedas mejor porque al no saber qué tanto es no sé si
llego en 1 día

**Comment by LeandroBraier** [comment]
Subido a Dropbox, carpeta PATY MAQUETADOR/ Patyviena

abrazo

**Comment by FAAREIA** [comment]
Ahi va la actualización. http://www.benteveo.tv/_patyviena2/
Unos detalles:
- Si bien el slideshow no rota solo, habría que buscar imágenes y no poner los productos solamente.
- A los productos también les faltan imágenes.
- Decime si esta bien que haya separado un mismo producto por cantidad (x6, x12, x24)

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

Correcciones:
1. No separes por cantidad. Hacé una entrada por producto con foto propia. Las fotos lindas que pusiste chiquitas abajo, ponelas arriba grandes en el slideshow y las que tenés grandes arriba ponelas chiquitas abajo. Quedarían solo 5 slides y, por ende, productos: Clásicas, Alemanas, Super, Scooby Doo y Largas. Si los tamaños de las fotos lindas no alcanzan para el slideshow, que el slideshow no rote, que sea sólo 1 imagen por ahora, la del inicio
2. Nos falta vuelta de diseño en el header, te acordás que habíamos dicho eso? Decime si no le encontrás la vuelta le pido a la diseñadora.
3. No usemos más imagenes con marca de agua. Porfa comprá o reemplazá la foto del formulario contacto.

Llegás con esto para hoy?

abrazo

**Comment by FAAREIA** [comment]
Si llego, las fotos de los productos sabes donde quedaron? no las puedo
encontrar en alta.

**Comment by FAAREIA** [comment]
Con respecto al header, habría que sentarse y pensar qué poner (contenido)
o con qué rellenar. Si lo pueden resolver, buenísimo.
Y otra cosa que me olvidaba, en el formulario no tiene mucho sentido el
campo "Título", lo sacamos o lo cambio por un "Asunto" al menos.

**Comment by LeandroBraier** [comment]
Te subí todo al dropbox, no?

¿Te referís a las que pusiste chiquitas abajo? Esas la verdad no recuerdo
de dónde salieron.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 10:02 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Exacto, cambialo por "Asunto", aunque lo ideal es que todos los asuntos
comiencen (como en Dánica) con el texto "Contacto Web".

Respecto del header se lo pido a la diseñadora no te preocupes

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 10:04 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
en el dropbox no estan, capas que nunca las tuve en grande y las recorte
desde el jpg de muestra.

**Comment by LeandroBraier** [comment]
puede ser. Entonces hacé como te digo. Dejá 1 solo slide por ahora, el que
tenemos en alta, y en las fotitos chiquitas de abajo poné los packs de los
productos.

Voy a pedirlas en alta a esas igual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 10:07 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, pregunta:
A las fotos chicas, vos decis de reemplazar las fotos por las imágenes de
los packs? Estoy viendo y poner más grande el pack implica distinguir el
producto de x6, x12 o x24.

**Comment by LeandroBraier** [comment]
Creo que no entiendo bien la pregunta. Si tenés que elegir 1 pack para
poner en imagen poné el más grande, pero abajo aclará: x6, x12 y x24
unidades.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 10:27 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, creo que ahora entiendo mejor. Lo que yo decis es que por producto hay
una foto y una imagen del pack. Pensé que quería reemplazar la foto por el
pack

**Comment by LeandroBraier** [comment]
Si, entendiste bien, reemplazá las fotos abajo por los packs. Cuando las
tengas en alta a las fotos las subimos pero al slideshow. De los packs, si
tenés varios del mismo producto elegí el más grande.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 10:45 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Fijate ahora Lea:
http://www.benteveo.tv/_patyviena2/

En el slideshow dejé 2 asi se puede interactuar con las flechas y el
ciruclo inferior.

**Comment by LeandroBraier** [comment]
Gracias!
1. Fijate si encontrás otra imagen para contacto, al cliente no le va a gustar.
2. Quitale el "Aquí va el título" y "Bajada genérica" por ahora.
3. Sumá un link en Paty que lleve a este sitio y uno en este sitio que lleve al de Paty.

abrazo

**Comment by FAAREIA** [comment]
Ok a todo, pero necesitaría saber que tipo de imagen busca el cliente.
Cuando busqué se me complicó con la variedad porque es necesario que la
mano, brazo o persona no este cortado en los costados.

**Comment by LeandroBraier** [comment]
La que estaba antes estaba perfecta. El único problema era que tenía marca
de agua.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 13:39 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, ahi estuve buscando y lo más similar que encontré fue esto:
http://sp.depositphotos.com/15645193/stock-photo-hungry-man-with-hot-dog.html?sst=240&sqc=248&sqm=8316&sq=3kjkkj
Le podemos clonar el brazo para alargarlo un poco, sirve?

**Comment by LeandroBraier** [comment]
Dale, probemoslo.

Consulta, podemos hacer que el slideshow tenga un aspect ratio más
cinemascope? Es decir, mismo ancho pero 70% del alto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 14:47 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si, eso no hay drama.
Sería 16:9 ?

**Comment by LeandroBraier** [comment]
Te paso la imagen, decime si la ves posible. La idea es que apenas cargue
la página se vea la lista de productos de abajo, al menos en PC en la
resolución media.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-10 15:09 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
no me llegó nunca la imagen lea

**Comment by LeandroBraier** [comment]
Fede, te pasé el header en Dropbox/PATYMAQUETADOR/PATYVIENA/Header

Subilo así vemos cómo queda.

abrazo

**Comment by LeandroBraier** [comment]
Fede, pudiste subir el header a PatyViena?

Te lo pasé hace 5 días, está acá:

Dropbox/PATY MAQUETADOR/PATYVIENA/Header

Subilo hoy así vemos cómo queda.

abrazo

**Comment by FAAREIA** [comment]
Si Lea, recien lo subi a:
http://www.benteveo.tv/_patyviena3/
Decime cualquier cosa

**Comment by LeandroBraier** [comment]
Está perfecto!

Gracias Fede!

Quitale los dos botones de Twitter y Facebook nomás y confirmame si el
formulario está funcionando. No lo quiero probar justamente por eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Quito los botones de Twitter y Facebook del sitio entero entonces?
El formulario funciona, pero yo lo recibo por ahora. Si queres probalo y te lo reenvio

**Comment by LeandroBraier** [comment]
Hecho!

Te hago 3 pedidos más:
1. Falta el mensaje de "pedido enviado" o algo por el estilo, como el que
   aparece en Paty. El de Paty dice: Gracias por contactarnos, le
   responderemos a la brevedad.

Porfa corregilo para ambos sitios y que diga así: Gracias por contactarnos.
Te responderemos a la brevedad.
1. ¿Podremos agregar en el fondo las mismas líneas y chirimbolos que en
   Paty? De esa forma quedan comunicadas ambas webs sin necesidad de que
   aparezcan como lo mismo. Hacelo pero en una versión paralela, así podemos
   ver ambas versiones y elegir una.
2. Hay que agregar, al pie y antes del footer de cada uno de los sitios, un
   link al otro sitio. Es decir, uno que lleve de Paty a Patyviena y viceversa.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ok a todo, pero eso de los links lo veo más como algo integrado al footer y
no antes. Si tuviesemos un listado de marcas puede ser, pero es solo 1

**Comment by LeandroBraier** [comment]
Ok, integrémoslo a los dos footer. Me parece buena la sugerencia.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-16 16:58 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, 
1. sigo viendo pixelado el logo de PAtyviena en el header. ¿Hay forma de mejorar esto?
2. ¿En qué url estás armando la segunda versión con fondo simil Paty?

**Comment by LeandroBraier** [comment]
Fede, el punto 2 quedó en suspenso, pero el 1 sigue igual. Lo sigo viendo pixelado. ¿Cuándo lo vas a subir de nuevo?

**Comment by FAAREIA** [comment]
Si queres lo cambio, pero al no tener el logo oficial, voy a usar el que puse en Paty, que lo saqué de google

**Comment by LeandroBraier** [comment]
OK, resolvamos así. La vaquita chiquita de arriba e slo que veo pixelado.
Cambialo con el archivo vectorizado que tenés de Paty, el logo de la marca
principal. La parte del logo que dice Paty Viena está OK.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi esta listo por ahora.

**Comment by LeandroBraier** [comment]
Lo subiste en este?

http://www.benteveo.tv/_patyviena2/

Creo que lo veo un poco mejor pero la diferencia no es tan grande, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, esta en:
http://www.benteveo.tv/_patyviena3/

**Comment by LeandroBraier** [comment]
Ahora si! Gracias Fede, quedó joya.

abrazo

**Comment by LeandroBraier** [comment]
Porfa ponele este link al link de Patyviena en el sitio de Paty.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya se lo puse ;)

**Comment by LeandroBraier** [comment]
Fede, tenemos feedback del cliente de esto también.
1. Buscarle la vuelta para que el logo de Patyviena en el header quede aplicado sobre blanco, no sobre una "curita"
2. La palabra Súper en la lista de productos está sin tilde en U.

abrazo

**Comment by FAAREIA** [comment]
![1](https://cloud.githubusercontent.com/assets/6184969/3877558/f210e9fa-2166-11e4-9bd6-b73cca82200c.png)
![4](https://cloud.githubusercontent.com/assets/6184969/3877559/f2166f9c-2166-11e4-8b83-13cf3a9fea94.png)
![3](https://cloud.githubusercontent.com/assets/6184969/3877556/f20a4ad2-2166-11e4-9719-d78e29b5b3c9.png)
![2](https://cloud.githubusercontent.com/assets/6184969/3877557/f20b559e-2166-11e4-8ca1-742ac48e3d7b.png)

Decime que te parece Lea, miralas a tamaño real asi las ves bien

**Comment by LeandroBraier** [comment]
Me gusta este Fede. 

https://cloud.githubusercontent.com/assets/6184969/3877559/f2166f9c-2166-11e4-8b83-13cf3a9fea94.png

Vamos con ese. Gracias!

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_patyviena4/
Sigo con lo de la línea negra del video de vimeo en IE.

**Comment by LeandroBraier** [comment]
Perfecto Fede!

Le agregarías el mismo Favicon de Paty también?

Gracias.

**Comment by LeandroBraier** [comment]
Fede, necesito también que quites el modo slideshow. Ya que tenemos una sola foto, que quede esa sola foto por ahora, sino flechitas que remiten a un slideshow. Si quitando la segunda foto alcanza para eso genial.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya esta listo

**Comment by LeandroBraier** [comment]
Resuelto! Gracias!

Me quedo el ticket.
